### ISSUE TITLE
Camera.main (same as FindObjectWithTag) called 8-24 times per frame 

### ISSUE THREAD

**Issue by MattOstgard** [leapmotion/UnityModules#1056]
Thought I should give a heads up on an optimization that might help. According to Unity Devs at Unite Europe 2017 you should cache Camera.main:
https://www.youtube.com/watch?v=_wxitgdx-UI&t=484s

What they say in the video:
> Camera.main...
> Calls Object.FindObjectWithTag("MainCamera")
> Every single time you access it.

According to the docs, this is still true in 2018.2.1f1 (what I am using):
https://docs.unity3d.com/ScriptReference/Camera-main.html

I did a test in the "Basic UI" scene and it was called an average of 13 times, at least 8, and at most 24 every frame. Hardware was an Oculus Rift + Rift Controllers + Leap Motion. Considering the work the Leap team has been doing for mobile support, I thought it was worth mentioning.

Found Camera.main references in these files:
- [Core/Examples/Example Assets/ProjectionPostProcessProvider.cs](https://github.com/leapmotion/UnityModules/blob/master/Assets/LeapMotion/Core/Examples/Example%20Assets/ProjectionPostProcessProvider.cs)
- [Core/Scripts/DetectionUtilities/FingerDirectionDetector.cs](https://github.com/leapmotion/UnityModules/blob/master/Assets/LeapMotion/Core/Scripts/DetectionUtilities/FingerDirectionDetector.cs)
- [Core/Scripts/DetectionUtilities/PalmDirectionDetector.cs](https://github.com/leapmotion/UnityModules/blob/master/Assets/LeapMotion/Core/Scripts/DetectionUtilities/PalmDirectionDetector.cs)
- [Core/Scripts/Utils/ConnectionMonitor.cs](https://github.com/leapmotion/UnityModules/blob/master/Assets/LeapMotion/Core/Scripts/Utils/ConnectionMonitor.cs)
- [Legacy/Attachments/Scripts/CameraFollower.cs](https://github.com/leapmotion/UnityModules/blob/master/Assets/LeapMotion/Legacy/Attachments/Scripts/CameraFollower.cs)
- [Legacy/UIInput/Scripts/LeapInputModule.cs](https://github.com/leapmotion/UnityModules/blob/master/Assets/LeapMotion/Legacy/UIInput/Scripts/LeapInputModule.cs)
- [Legacy/UIInput/Scripts/PhysicsUI.cs](https://github.com/leapmotion/UnityModules/blob/master/Assets/LeapMotion/Legacy/UIInput/Scripts/PhysicsUI.cs)
- [Modules/InteractionEngine/Examples/6. Dynamic UI/Scripts/WorkstationBehaviourExample.cs](https://github.com/leapmotion/UnityModules/blob/master/Assets/LeapMotion/Modules/InteractionEngine/Examples/6.%20Dynamic%20UI/Scripts/WorkstationBehaviourExample.cs)
- [Modules/InteractionEngine/Examples/Common Example Assets/Scripts/SimpleFacingCameraCallbacks.cs](https://github.com/leapmotion/UnityModules/blob/master/Assets/LeapMotion/Modules/InteractionEngine/Examples/Common%20Example%20Assets/Scripts/SimpleFacingCameraCallbacks.cs)
- [Modules/InteractionEngine/Scripts/Internal/DefaultXRNodeTrackingProvider.cs](https://github.com/leapmotion/UnityModules/blob/master/Assets/LeapMotion/Modules/InteractionEngine/Scripts/Internal/DefaultXRNodeTrackingProvider.cs)

**Comment by nickjbenson** [comment]
Thanks for the heads-up. Yes, we should definitely remove these calls and replace them with caching.

**Comment by MattOstgard** [comment]
This has been resolved on Unity's side for 2020.2+: https://blogs.unity3d.com/2020/09/21/new-performance-improvements-in-unity-2020-2/
