### ISSUE TITLE
How to use Leap.Hand.StabilizedPalmPosition data?

### ISSUE THREAD

**Issue by Kidodelog** [leapmotion/UnityModules#1057]
How can I use the data from StabilizedPalmPosition? It always return the coordinate of the LeapServiceProvider's transform position. Thank you.

I'm developing for Desktop Mode.

**Comment by nickjbenson** [comment]
StabilizedPalmPosition is an older API field that is no longer supported. As a to-do for this ticket, we should make sure it's marked deprecated in LeapCSharp.

Use PalmPosition instead; it's as stable as it's going to get. If you need it to be smoother in exchange for higher latency, you can filter the value in a script with e.g. a rolling average. There's a RingBuffer class built in to Core that can be used to accumulate values over the last N frames.

**Comment by Kidodelog** [comment]
Thank you. :D
