### ISSUE TITLE
GraphicRenderer module is not compiling when importing to recent versions of Unity

### ISSUE THREAD

**Issue by upeksha1996** [leapmotion/UnityModules#1059]
Following are the errors logged in console

> Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Utility/AtlasBuilder.cs(445,53): error CS1503: Argument `#3' cannot convert `UnityEngine.TextureFormat' expression to type `UnityEngine.Experimental.Rendering.GraphicsFormat'

> Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Utility/AtlasBuilder.cs(445,19): error CS1502: The best overloaded method match for `UnityEngine.Texture2D.Texture2D(int, int, UnityEngine.Experimental.Rendering.GraphicsFormat, UnityEngine.Experimental.Rendering.TextureCreationFlags)' has some invalid arguments

> Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Utility/AtlasBuilder.cs(384,23): error CS0122: `UnityEngine.Texture2D.Texture2D(int, int, UnityEngine.Experimental.Rendering.GraphicsFormat, UnityEngine.Experimental.Rendering.TextureCreationFlags, System.IntPtr)' is inaccessible due to its protection level

**Comment by nickjbenson** [comment]
These issues occur in recent versions of Unity (2018.2 or so) because Unity changed some texture-related function arguments in a non-backwards-compatible way. (Specifically, `mipmap` was renamed to `mipChain` for some reason.)

We haven't added the fix to UnityModules yet, but will soon. In the mean time, AtlasBuilder can be fixed for recent versions of Unity with the following replacements:

Near line 384:
```
      #if UNITY_2018_2_OR_NEWER
      packedTexture = new Texture2D(1, 1, TextureFormat.ARGB32, mipChain: false,
        linear: true);
      #else
      packedTexture = new Texture2D(1, 1, TextureFormat.ARGB32, mipmap: false,
        linear: true);
      #endif
```

And near line 445 (about 450 after the above fix):
```
        #if UNITY_2018_2_OR_NEWER
        texture = new Texture2D(3, 3, TextureFormat.ARGB32, mipChain: false);
        #else
        texture = new Texture2D(3, 3, TextureFormat.ARGB32, mipmap: false);
        #endif
```

**Comment by zook111** [comment]
I also had to change line 342
```
#if UNITY_EDITOR
            UnityEditor.EditorUtility.CompressTexture(tex, _format, TextureCompressionQuality.Best);
#endif
```

to 

```
#if UNITY_EDITOR
            UnityEditor.EditorUtility.CompressTexture(tex, _format, UnityEditor.TextureCompressionQuality.Best);
#endif
```

**Comment by Ultraleap-Dan** [comment]
The Graphic Renderer module has been deprecated and this will not be addressed.
