### ISSUE TITLE
RiggedHand "SetEditorLeapPose" command leaks pose state onto its bone Transforms

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#1068]
This checkbox on RiggedHand components should use the current state of the RiggedHand to move the skinned mesh hand to match the edit-time hand pose. However, if the Rigged Hand is misconfigured, checking and unchecking this box will apply successive 90-degree rotations to the bones of the skinned hand mesh, which cannot be undone with the Undo command.

**Comment by Tidne** [comment]
This problem still exists, have you thought of a better solution?

**Comment by Ultraleap-Dan** [comment]
The hands module is being reworked and this will be superseded by https://github.com/leapmotion/UnityModules/pull/1157
