### ISSUE TITLE
InteractionModules

### ISSUE THREAD

**Issue by EngineerZhang** [leapmotion/UnityModules#1069]
Hi, when i grasp the object in the scene, I find the hands model will penetrate model,how can i avoid it to be real？Thanks！

**Comment by capnmidnight** [comment]
Add kinematic colliders to each of the joints

**Comment by nickjbenson** [comment]
Physically depenetrating hands from grasped objects can be solved in a couple of ways, none of which are trivial, and none of which are scoped for the Interaction Engine right now.

One of the reasons we didn't go down this path was that we've tried this before, and it feels bad in VR. That's a subjective stance, but it's where we all stood when considering the feature.
