### ISSUE TITLE
feat-multi-device - Multi-Device scene can't start

### ISSUE THREAD

**Issue by Striffly** [leapmotion/UnityModules#1070]
There are several errors present during the launch of the Multi-Device scene with a clean project, could you fix them ?

Environment : 
 * Unity 2018.3.0f2
 * Orion 4.0.0+52238
 * Windows 10 x64

Steps to reproduce : 
 * Copy LeapMotion folder to Unity
 * Launch Multi-device scene

![capture](https://user-images.githubusercontent.com/13284087/50543459-72013000-0bd9-11e9-9d22-41a5d77915c4.PNG)

![capture](https://user-images.githubusercontent.com/13284087/50543487-2a2ed880-0bda-11e9-8ca5-d9d3ef7bb4fb.PNG)
![capture](https://user-images.githubusercontent.com/13284087/50543491-429ef300-0bda-11e9-9036-a01dfeae2644.PNG)
![capture](https://user-images.githubusercontent.com/13284087/50543493-577b8680-0bda-11e9-9e7e-d8eb6ef6f243.PNG)

**Comment by nickjbenson** [comment]
Multi-device support was built for an earlier version of Unity; these errors don't pertain to multi-device support specifically, they're just Unity API changes in 2018.3.

If you don't need the Graphic Renderer, I would recommend commenting out the problematic sections in AtlasBuilder.cs, or deleting the Graphic Renderer folder altogether. The fixes for these issues shouldn't be tricky if you needed Graphic Renderer support, however.
