### ISSUE TITLE
feat-multi-device Hands will duplicate across Service Providers when insufficient Leaps are connected

### ISSUE THREAD

**Issue by rorygames** [leapmotion/UnityModules#1071]
Creating a scene with multiple Leap Service Providers will cause hand data to be duplicated across any assigned a value greater than the number of individual Leap Motions connected. This occurs both when setting a Leap Service Provider to either a serial number or when using a device array index.
Feels as though it is the opposite of what should be occurring?
Any subsequent Leaps connected during run time will start overriding their correct index or serial number.

![image](https://user-images.githubusercontent.com/6281246/50763060-ab374100-1266-11e9-9d61-c285ec58a9d2.png)
Two devices connected, Service Providers 1, 3 and 4 using hand data from device 1. Device 2 is covered and thus not reporting anything. When device 3 is connected (either during run time or before playing) the 3rd Service Provider will start operating uniquely.

Running in Unity 2018.3.0f2, tested in both Editor and Built projects on multiple machines.

**Comment by zlremillard** [comment]
I'm having the same problem here to handle multiple devices in the same project. Did you end up finding a solution?
