### ISSUE TITLE
feat-multi-device Incorrect hand positions from LeapServiceProvider if LeapXRServiceProvider also in use

### ISSUE THREAD

**Issue by rorygames** [leapmotion/UnityModules#1076]
Using both a LeapServiceProvider and a LeapXRServiceProvider in a scene will cause the LeapServiceProvider to operate incorrectly, generally causing it to map to opposite hands (e.g. left hand will activate right hand model in the left side). This will consistently occur when both hands are present above the LeapServiceProvider, however it will generally get singular hands correct.

![image](https://user-images.githubusercontent.com/6281246/51324274-3502bd80-1a62-11e9-860f-d8888139656a.png)
The Leap further away is the one attached to the VR headset (correct data, using XR provider), the closer set of hands are the ones on the desk (incorrect data, using standard provider).

[Video of issue.](https://i.imgur.com/GU6tb4D.gifv)

Issue is not present when only using LeapServiceProviders in the scene, however the VR benefits of the XR provider are all negated.

**Comment by jselstad** [comment]
There's a service-wide flag that gets set when an XR Provider is in use that optimizes hand initialization for HMD-mode.   Decoupling that on a per-device status is not in the roadmap at the moment.

You can set that flag explicitly the same way it's set here:
https://github.com/leapmotion/UnityModules/blob/master/Assets/LeapMotion/Core/Scripts/LeapXRServiceProvider.cs#L333-L334

Perhaps you can contextually detect between the situations and set the flag appropriately?
