### ISSUE TITLE
Unimplmented API features

### ISSUE THREAD

**Issue by Naphier** [leapmotion/UnityModules#1077]
Hi, 
We've been waiting a while for some featues like Device.IsSmudged and Device.IsLightingBad to be implemented.  Any idea when this might happen?

**Comment by nickjbenson** [comment]
Ultimately those features didn't make the cut and are not on the API roadmap going forward. It's likely those calls will hang around for compatibility reasons for the time being, just in case someone is referencing the functions (even if they aren't using them).
