### ISSUE TITLE
AtlasBuilder.cs not compiling with Unity 2018.3

### ISSUE THREAD

**Issue by julienkay** [leapmotion/UnityModules#1078]
Unity moved the TextureCompressionQuality enumeration to the editor namespace in 2018.3.
The following call to CompressTexture():

https://github.com/leapmotion/UnityModules/blob/127374083128adbe6699c1ca96784a6d15d508f8/Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Utility/AtlasBuilder.cs#L343

needs to be changed to:

`UnityEditor.EditorUtility.CompressTexture(tex, _format, UnityEditor.TextureCompressionQuality.Best);`

**Comment by nickjbenson** [comment]
This should be fixed as of the 4.5.0 release.
