### ISSUE TITLE
Assest not working with unity.

### ISSUE THREAD

**Issue by andresmitre** [leapmotion/UnityModules#1079]
Hello, 

I did not know where to post this. But I haven't been able to run a scene in unity using the leap motion. I followed the instructions from the [official website](https://developer.leapmotion.com/unity/#5436356) and I also followed the instructions from a [YouTube video](https://youtu.be/Wh3YK2OcI4M), not successful. Anyone has any clue what I may be doing wrong? 

I've tried different assets versions, but none is working. 

- Leap_Motion_CoreAssets_4.2.1
- Leap_Motion_Core_Assets_4.3.4
- Leap_Motion_CoreAssets_4.40

I also tried with Leapmotion V2 and the Orion. 

Thanks.

**Comment by gamodulon** [comment]
Can you please provide more information on what specifically is not working?

e.g.
- Have you tried the diagnostic visualizer. If you did, are hands showing up in the view?
- Are you getting any errors in Unity console?
- What version of Unity are you using?

**Comment by wnk99** [comment]
HI! I am having the same problem! My hands are showing up in the diagnostic visualizer. I am getting this error "warning CS0618: 'PrefabType' is obsolete: 'PrefabType no longer tells everything about Prefab instance.'. I am using Unity Hub 2.0.3

**Comment by andresmitre** [comment]
I ended using another laptop. I Could not figure it out what was the problem. The one that gave me problems had the next specs:

Intel i7-6500U CPU @ 2.50GHz
64-bit Windows 10

I do not remember the problem I was dealing with using Linux. But It may be my computer. Once I switched everything worked like a charm at the first try.

**Comment by nickjbenson** [comment]
Closing since the primary issue is resolved. I'm not sure what the issue was but I'd need more details to figure out what went wrong. If someone else is having an issue, please file a fresh ticket and we can dive in there.
