### ISSUE TITLE
Interaction Engine- Grab not working properly.

### ISSUE THREAD

**Issue by junglee372018** [leapmotion/UnityModules#1081]
Hi,
when i try to grab objects in the scene only one object is working, remaining objects grab  is not working.
even when i duplicated the same object also it is not working.

**Comment by nickjbenson** [comment]
Sorry, I'll need more specifics about the issue to be able to answer your question here.

Grabs through the Interaction Engine should generally work as long as your objects are Rigidbodies with Colliders and InteractionBehaviour components. You'll also only be able to grab one object at a time with a given hand.

**Comment by junglee372018** [comment]
Hi,
Thankyou for the reply. Actually there was an issue with SteamVR, resetting the steam solved the issue.
