### ISSUE TITLE
69+17 Warnings in Unity 2019.1.3f1 and 159 Warnings in Unity 2019.1.2f1

### ISSUE THREAD

**Issue by Zacrain** [leapmotion/UnityModules#1083]
Hello,

I wanted to inform you that the newest version of Unity (2019.1.2.f1) throws 159 warnings corresponding to LeapMotion.

On my system: https://pastebin.com/265chmXg

Hope this helps.

**Update**
In the even newer version 2019.1.3f1 the warning count has reduced to 69 warnings: https://pastebin.com/7zhrTQz6
And 16 additional ones complaining about several lighting data assets and 1 about a mesh:
```
ImportFBX Warnings: 
Can't generate normals for blendshape 'Key 1' on mesh 'Cube', mesh has no smoothing groups.
Lighting data asset ‘LightingData’ is inconsistent because 2 files out of 10 are missing.  Please use Generate Lighting to rebuild the lighting data.
[...]
```

**Comment by nickjbenson** [comment]
It's true, at present, 2019 has lots of import warnings. Incremental UnityModules changes to address this are slowed down right now as we will possibly be making larger changes to the Unity SDK.

If the warnings become frustrating enough that you wind up fixing them yourself, I'd be happy to review a PR, unfortunately some of the warnings get into the weeds on the specifics of, e.g., Unity's changes to prefabs and are a little sticky for that reason.

**Comment by macbl** [comment]
The LeapMotion scripts will actually also cause a substantial freeze in the editor (likely due to the countless warnings). I my case after each script compilation the editor freezed for 20 seconds. Is there any work done on the LeapMotion Unity integration? Or is this dead?

**Comment by nickjbenson** [comment]
Release 4.5.0 moves the LeapMotion to the Plugins folder to reduce compilation times, and also implements a bunch of changes to get rid of warnings in Unity 2019. If any new obnoxious warnings pop up for Unity 2019, please open up a new ticket and we can take a look. :)
