### ISSUE TITLE
How to get 640 x 480 pixels raw images

### ISSUE THREAD

**Issue by sienori** [leapmotion/UnityModules#1087]
I want to get 640 x 480 pixels raw images in Unity.
I implemented in the following way and got images of 640 x 240 pixels.

``` GetLeapImage.cs
public class GetLeapImage : MonoBehaviour{

    private LeapServiceProvider _provider;
    private Controller _controller;

    private void Awake()
    {
        _provider = GetComponent<LeapServiceProvider>();
        _controller = _provider.GetLeapController();
        _controller.ImageReady += OnImageReady;
    }

    private void OnImageReady(object sender, Leap.ImageEventArgs args)
    {
        Debug.Log(args.image.Width + ", " + args.image.Height); // 640, 240
    }
}
```

Using [LeapUVC](http://blog.leapmotion.com/leapuvc/), it seems that I can get 640 x 480 pixels images.
Can I get large images in Unity?

**Comment by nickjbenson** [comment]
I don't believe this is possible currently with the our LeapC API through Unity. I do expect some changes down the pipe for the API in the coming months, but I don't have any specifics on that right now.

**Comment by sienori** [comment]
@nickjbenson
Ok, thank you for the answer!
