### ISSUE TITLE
The hand model flies forward in either the LWRP or the HDRP.(手部模型在LWRP或者HDRP中会向前飞。)

### ISSUE THREAD

**Issue by li2412360774** [leapmotion/UnityModules#1092]
Unity Version:2019.2.14f1
LeapMotion:4.4.0

With HDRP or LWRP, the hand will fly forward but when I replace the Leap XR Service Provider with the Leap Service Provider, I can use it.(使用HDRP或者LWRP时手会向前飞但是当我将Leap XR Service Provider 替换成 Leap Service Provider时，就可以用了。)

**Comment by alex-eyre** [comment]
I'm also experiencing this issue with the following setup:
 - Vive Pro
 - Unity 2019.3.1
 - LeapMotion 4.4.0
 - LWRP (now the URP but same thing)
did you ever fix the issue @li2412360774?

**Comment by jselstad** [comment]
Should be fixed in [Release 4.5.0](https://github.com/leapmotion/UnityModules/releases/tag/UM-4.5.0) :+1:
