### ISSUE TITLE
Forearm in rigged hand

### ISSUE THREAD

**Issue by BeaXR** [leapmotion/UnityModules#1094]
Good morning,
I'm trying to use a full-rigged model of a hand with the LeapMotion Orion. Particularly, I need to update the RiggedPepperFullHand (v2.3) to v4.4. Everything works well with models without the forearm (RiggedPepperCutHand), however with the global model the arm doesn't' work properly.
I thought that it would have been sufficient to select the forearm bone and drag&drop it into the RiggedHand. Forearm field, but it doesn't work. I've seen that the bones' hierarchy in the prefab (v2.3) is different from the one in the model (always v2.3). Maybe it is the issue, but I don't know how to modify it. Can you help me, please?
Thank you very much in advance!

**Comment by brandonjmatthews** [comment]
I recently managed to get both the old "Salt" and "Pepper" hands (with forearms) to work with Orion. It's a bit of a struggle as the bones don't appear to align with the default Orion hand structure.

I have created a Unity Package which you can download [here](https://github.com/brandonjmatthews/leap-realistic-hands-orion/releases/tag/0.1). Let me know if you have any issues.

**Comment by BeaXR** [comment]
Thank you very much @brandonjmatthews 
I've tried your unitypakage and it works! 
Only a side note, I've noticed that the bones of the "SaltBaseFullRightHand" were not defined in the example scene, but I've just followed the "PepperBaseFullRightHand" setup and all of them works great now! Thanks
