### ISSUE TITLE
Tests location change in Core

### ISSUE THREAD

**Issue by CDiaz-MS** [leapmotion/UnityModules#1097]
There are tests located in the Core folder that could be moved to a separate tests directory.

An issue with the multiple test file locations is when an asmdef is placed at the root of Core, an additional 7 separate asmdefs are needed for the tests.

Paths of the tests in Core:
- Core/Editor/Tests/
- Core/Plugins/LeapCSharp/Editor/Tests/
- Core/Scripts/Algorithms/Editor/Tests/
- Core/Scripts/DataStructures/Editor/Tests/
- Core/Scripts/Encoding/Editor/
- Core/Query/Editor/
- Core/Scripts/Utils/Editor/
  - This folder contains tests and utils

**Comment by nickjbenson** [comment]
This should be fixed as of release 4.5.0; If another tests assembly issue pops up, we can re-open and address.
