### ISSUE TITLE
Core Assets version 4.5.0 lists 4.4.0 in Version.txt

### ISSUE THREAD

**Issue by CDiaz-MS** [leapmotion/UnityModules#1104]
The version number in the new Unity Core Assets 4.5.0 lists 4.4.0 in the Version.txt on the rc-4.5.0 branch.

https://github.com/leapmotion/UnityModules/blob/2cfcd412607b20fa8b3aad0c219deac3ad41e8ff/Assets/Plugins/LeapMotion/Core/Version.txt#L1

**Comment by nickjbenson** [comment]
Fixed, and the unitypackage build in the 4.5.0 release tag has been updated accordingly.
