### ISSUE TITLE
Core Assets 4.5.0 Import Error into Unity 2018.4

### ISSUE THREAD

**Issue by CDiaz-MS** [leapmotion/UnityModules#1106]
On import of the 4.5.0 core assets into Unity 2018.4.22, the following error is logged

```
Assets\Plugins\LeapMotion\Core\Scripts\LeapXRServiceProvider.cs(338,45): error CS0246: The type or namespace name 'ScriptableRenderContext' could not be found (are you missing a using directive or an assembly reference?)
```

The fix is the missing UnityEngine.Experimental.Rendering namespace.

After the adding the namespace, the following error is also in the console:

```
Assets\Plugins\LeapMotion\Core\Scripts\LeapXRServiceProvider.cs(243,31): error CS0117: 'RenderPipelineManager' does not contain a definition for 'beginCameraRendering'
```

**Comment by jselstad** [comment]
Fixed in https://github.com/leapmotion/UnityModules/commit/d503f9b4a7b10ad072d94858a782e9c92699bf0a , this means that ScriptedRenderPipelines are disabled in pre-2019.1 versions due to the fact that the SRP did not gain the requisite callback for TemporalWarping until it was made a non-experimental feature in 2019.1.

**Comment by nickjbenson** [comment]
And that commit is now in the pending hotfixes PR, #1107. @CDiaz-MS, we'll continue to pull further ticket fixes into that PR so the hotfixes can all be applied at once to the release. It'd be helpful to have a note from you when you've finished your review of the release on the MS side, so we can then merge the patches in. :)

**Comment by CDiaz-MS** [comment]
Hi @nickjbenson , since the hotfix PR is pending, there are still obsolete warnings in both unity 2018.4 and 2019.3.  It would be awesome if we could fix these, but it is not necessary.

The obsolete warnings for 2018.4 are in Utils.cs
```
Assets\Plugins\LeapMotion\Core\Scripts\Utils\Utils.cs(2306,7): error CS0618: 'TextureFormat.ETC_RGB4_3DS' is obsolete: 'Nintendo 3DS is no longer supported.'
```

For 2019.3, they are all in the XRSupportUtil.cs

```
Assets\Plugins\LeapMotion\Core\Scripts\Utils\XRSupportUtil.cs(50,26): error CS0618: 'XRDevice.userPresence' is obsolete: 'This is obsolete, and should no longer be used.  Please use CommonUsages.userPresence.'

```

**Comment by nickjbenson** [comment]
I'll look into getting those addressed as well, thanks for flagging. Should have the hotfix wrapped up soon.

**Comment by CDiaz-MS** [comment]
Thanks @nickjbenson, I have finished my testing and have not encountered any further issues.

**Comment by nickjbenson** [comment]
Hotfixes have been merged and applied. Closing!
https://github.com/leapmotion/UnityModules/releases/tag/UM-4.5.0
