### ISSUE TITLE
Building a LeapMotion Unity Project

### ISSUE THREAD

**Issue by txusillo** [leapmotion/UnityModules#1124]
Hello,

I am experiencing a bug building a Leap Motion project in Unity. Whenever I play this project in editor mode works like a charm, but whenever I run the build, the LeapMotionController does not work.

In my scene, I have a Leap Service Provider and Leap Image Retriever components attached to one GameObject. I retrieve the image from the IR and do some stuff with it.

I am using Unity 2019.4.1f1.

**Comment by zalo** [comment]
Do you have the `XRlegacyInputHelper` installed?  Do you have logs or errors from the built/editor project?

We're rolling up a new release of UnityModules which contains a number of fixes (some specifically for 2019.4):
https://github.com/leapmotion/UnityModules/pull/1126

I've tested 2019.4 builds with this and they appear to be working in the `Assets/Plugins/LeapMotion/Core/Examples/Capsule Hands (VR - Infrared Viewer).unity` scene.

**Comment by Ultraleap-Dan** [comment]
We believe the this is resolved by https://github.com/leapmotion/UnityModules/pull/1126 and this issue is now closed.
