### ISSUE TITLE
[InteractionModule] Strange InteractionBehavior behavior if its moving

### ISSUE THREAD

**Issue by dobryc** [leapmotion/UnityModules#1125]
I am developing a kind of train driving simulator using leap motion. In the cockpit i have some InteractionBehavior powered levers. Everything is fine, while train has no speed, but when it does, some weird things happening - it looks like physical objects (rigidbody) lag behind its meshes, so interaction with those happens with offset. The higher the speed, the greater the offset. If i stop the train, interaction will work as expected.

Here is a simple illustration of this behavior :
Speed = 0, works as expected
![1](https://user-images.githubusercontent.com/11852501/94937110-d2708000-04d7-11eb-8deb-3b2f6b5345be.png)
Speed ~ 50km/h - i can interact with cube from this far, but cant at cube mesh's position.
![2](https://user-images.githubusercontent.com/11852501/94937113-d3a1ad00-04d7-11eb-98d8-37e98031e1db.png)

The cube is simple kinematic rigidbody with full constraints, placed in the train hierarcy.
LeapRig also just placed in the train hierarcy.

Any workaround?

**Comment by nickjbenson** [comment]
There's an example scene in the IE that demonstrates the right scene setup for being in a moving reference frame, called, handily, Moving Reference Frames :)

Basically you just need to put your InteractionManager object as a child of something that inherits the motion of the train (so usually it's like, Train parents Player parents InteractionManager), but it could also be something like "dynamically make the InteractionManager a child of the Train while the player is on the train". One of those options could probably work for your situation?

**Comment by dobryc** [comment]
> There's an example scene in the IE that demonstrates the right scene setup for being in a moving reference frame, called, handily, Moving Reference Frames :)
Oh, I hadn't saw this for some reason, sorry, I'll give it a try tomorrow. I do believe it will help, cause this weird behaviour kept me awake for two days in a row.

**Comment by Ultraleap-Dan** [comment]
Hi @dobryc, please can you let me know if this suggestion resolved the issue?

**Comment by dobryc** [comment]
Hey @Ultraleap-Dan !
Shame on me for not replying it back.
Yes, after a many iterations and tries, thanks for the example, I managed to reach expected behaviour.
Thank you, guys for help and amazing leapmotion!
