### ISSUE TITLE
Leap Rig not worked at RunTime in Unity 2020.1.17

### ISSUE THREAD

**Issue by Ehsan-Akhlaghy** [leapmotion/UnityModules#1153]
Hello,
I Created a prefab which contain LeapRig Leap motion, I have to instantiate the prefab at runtime, but first of all when prefab cloned, LoPoly Rigged HandLeft  and LoPoly Rigged Hand Right which is child of LeapRig, cloned although there is one copy of them as gameobject in scene, Second when my Real Hands are in Field of View of Leap motion, no tracking happened, I have to Activate and DeActivate LoPoly Rigged Hand Right and Left in order to Tracking happened. please look at link below which is atteched at drive
what is problem?

https://drive.google.com/file/d/1vHg0kwWmW2wJZtxNrZCuy3wIdxA8epgb/view?usp=sharing

Best Regard 
EA

**Comment by Ultraleap-Dan** [comment]
We are currently investigating this issue.

**Comment by Ultraleap-Dan** [comment]
Please check that the RiggedHands are assigned HandModelManager after you have instantiated it.

![image](https://user-images.githubusercontent.com/59871906/123079299-b620c480-d413-11eb-8db4-2ba98240a439.png)
