### ISSUE TITLE
HDRP Passthrough Background Shader 

### ISSUE THREAD

**Issue by annapompermaier** [leapmotion/UnityModules#1155]
By using the HDRP in Unity, the shaders must be rewritten. Have someone already done it and would share it here? I tried but failed!
I need the IR Camera View inside Unity to work in HDRP!
Thank you all in advance!
![WhatsApp Image 2021-02-12 at 10 35 08](https://user-images.githubusercontent.com/62881755/108858196-2d705400-75ec-11eb-813e-3bf612d84a7c.jpeg)

**Comment by Ultraleap-Dan** [comment]
This has been resolved by https://github.com/leapmotion/UnityModules/pull/1156
