### ISSUE TITLE
HandDrop destination seems fairly random

### ISSUE THREAD

**Issue by jo3w4rd** [leapmotion/UnityModules#117]
The position to which the hand model returns when tracking is lost seems fairly random. It isn't the starting point in the scene and it isn't the first tracked position of the hand. Just holding a hand steady in the Leap field of view and then covering the leap with the other hand so that the tracking is abruptly lost will result in the tracked hand model "dropping" to different positions on successive repetitions.

There is also a problem when hand re-identification occurs. If the hand switches chirality, the old hand remains stuck in the position of the switch. Oddly, in this case, the destination is consistent -- it doesn't move at all.

**Comment by jo3w4rd** [comment]
This probably occurs because of the null reference exception thrown when the hand leaves the view.

**Comment by protodeep** [comment]
Tested this a bunch while working on autorigging, and seems to do what its supposed to do.  But this TransitionBehavior will get reworked for the next Hands Module release.

**Comment by jo3w4rd** [comment]
Part of the problem does seem to be fixed, the destinations are no longer random. It seems, though that spawned models drop to a much different point than instance models. And if you use prefabs without instances those go to a third place (though one set does get stuck in the first position).

Also, this script requires a palm member on the hand, so it will only work with HandModel instances, not IHandModel instances -- and no warning is given and no null check is made to prevent the runtime error.

**Comment by protodeep** [comment]
Ah, that's all helpful.  Thank you.

**Comment by nickjbenson** [comment]
@protodeep Issue is pretty old, if there's no plan to make progress in the near future and/or the issue is stale, I think we should close it.
