### ISSUE TITLE
Decide upon consistent coding style

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#124]
We have a lot of inconsistencies, with different styles being added in different places.

Includes:
- tab width?
- braces on end of line or next?
- Use braces for single line if/while statements
- variable naming (private/protected/public)
- method naming (private/protected/public)

Once we decide on a standard, we can all set up our visual studio settings to conform to the same standard, that way whenever submitting a PR, people don't end up changing unrelated code because they wanted to auto-format.

**Comment by Amarcolina** [comment]
My proposal:
- 2 space width
- braces on end
- always use braces, even for single line if/while statements
- _name for private, name for protected/public
- name for private/protected, Name for protected/public

**Comment by protodeep** [comment]
Agreed here.  @jo3w4rd That work for you?

**Comment by jo3w4rd** [comment]
Sure.

**Comment by ajohnston33** [comment]
This bit is ambigious:
  _name for private, name for protected/public
  name for private, Name for protected/public

Can I vote for the first line everywhere?  Or is it too late to change that.

**Comment by Amarcolina** [comment]
Yeah nothing is set in stone at all.  That part might have been a little ambiguous, the first line was talking about variables and the second line was talking about methods. Is your request to have _name for both private variables and methods?

**Comment by Amarcolina** [comment]
[VC_CSharp.zip](https://github.com/leapmotion/UnityModules/files/207025/VC_CSharp.zip)
Here is a settings file that we can all use to setup the CSharp text editing settings.

**Comment by Amarcolina** [comment]
Once the settings are loaded, you can auto-format a file by first pressing CTRL+K, then CTRL+D
