### ISSUE TITLE
I can‘t find Gesture class, please tell me how to use Gesture, thanks

### ISSUE THREAD

**Issue by zhenfeng-zhu** [leapmotion/UnityModules#132]
help me!

**Comment by testmasterbright** [comment]
The gesture class was deprecated in the Orion Unity Core Assets. Make sure you are looking at the correct Unity docs: https://developer.leapmotion.com/documentation/orion/unity/index.html

We do offer a pinch detector in the Pinch Utilities Module:
https://developer.leapmotion.com/documentation/orion/unity/unity/Unity.LeapPinchDetector.html

**Comment by jo3w4rd** [comment]
Not just deprecated. Gestures were removed altogether.

**Comment by zhenfeng-zhu** [comment]
thanks
