### ISSUE TITLE
Leap.Finger.TransformedCopy doesn't propagate the fingerId correctly

### ISSUE THREAD

**Issue by cherullo** [leapmotion/UnityModules#15]
The Finger constructor sets 

`_id = (handId *10) + fingerId`

The fingerId itself is not stored in the Finger class. Later, when TransformedCopy is called, this _id is passed as fingerId to the constructor, which once again adds handId * 10.
The result is that the Id of the transformed copy is different from the original object.

**Comment by jo3w4rd** [comment]
Fixed by platform #5561
