### ISSUE TITLE
Investigate version system

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#155]
It would be nice to have a version stored inside the core package that is updated for every new release.  It would also be nice if each module specified a minimum core version so that we can prevent users from trying to use modules with a version of the core that is not supported.

**Comment by protodeep** [comment]
So, would a readme for core and each module do the trick?

**Comment by protodeep** [comment]
Duplicate of #13

**Comment by Amarcolina** [comment]
I mean a way that is stronger than a readme.  Something that can actually actively warn a user as opposed to requiring them to find a file that they may not know about.  Not sure the best approach, but something to brainstorm for sure.

**Comment by nickjbenson** [comment]
@Amarcolina I'm not sure this is worth the effort. Usually a user upgrading is just expected to upgrade Core and all Modules at the same time; in addition, we'd have to start tracking how fore back a given Core release could be before a Module would stop working with it.

**Comment by Amarcolina** [comment]
I agree, I'm going to close this
