### ISSUE TITLE
Fix incorrect logic for device type

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#160]
In LeapServiceProvider we are still using the incorrect serial number logic to determine device type, this should be fixed because it forces developers with devices that do not follow the pattern to check the 'override device type' checkbox, which shouldn't need to exist at all.

**Comment by nickjbenson** [comment]
@jselstad @Amarcolina We should just remove the device type entirely for the next Core release, unless someone has a compelling argument for keeping it?

**Comment by Amarcolina** [comment]
We need to first verify that we have a good alternative.  We originally created it because the leap API didn't provide enough data to make all of our decisions.  If we can get all the data we need from the API then we can get rid of this.
