### ISSUE TITLE
[Feature Request] Support Desktop Mode for XRServiceProvider

### ISSUE THREAD

**Issue by camnewnham** [leapmotion/UnityModules#1600]
I've recently been using an Ultraleap for testing UI targeting HoloLens2 and Quest devices. So far, this has been working very well and it's been an excellent mechanism for improving UI iteration time and debugging.

The goal here is:
- Use the screen-based "XR Device Simulator" sample provided by Unity (to avoid putting on and removing a headset during development)
- Use an Ultraleap in Desktop mode to add detailed hand simulation (to avoid using keyboard/mouse to control complex hands)
- Use the on-device hand tracking inbuilt in HoloLens/Quest at runtime.

The **XR**ServiceProvider is needed (as opposed to the regular service provider...) because we need to position the ultraleap relative to the camera (via setting the device origin), except that rather than having it _on_ the camera as would be typically for HMD XR, it's at a relative offset that approximates where the desk is relative to my seated position.

I've worked around this by [extending the service provider](https://gist.github.com/camnewnham/335e69074b170ceffc6b3809a046fe98) to set the appropriate policy and some other useful configurations for this purpose.

I created [a Pre and Post processor](https://gist.github.com/camnewnham/94679e670189dfe781e4421c4277e2d2) to disable and re-enable Ultraleap in the editor when building to run on device.
 
Two requests:
1. Could desktop mode be supported in the `LeapXRServiceProvider` ? Or alternatively, could a third service provider be supported?
2. Could there be an option to only enable the Leap XRHands Subsystem in editor mode?

**Comment by MattGrayUL** [comment]
As a completely alternative solution. The LeapServiceProvider in Desktop mode will position the hands relative to the Transform of the Gameobject that the LeapServiceProvider component is attached to.

This means you would be able to position the LeapServiceProvider GameObject the same way that you do with your proxy [here](https://gist.github.com/camnewnham/335e69074b170ceffc6b3809a046fe98#file-desktopleapxrserviceprovider-cs-L14)

However, as I have just checked, the XRHands Subsystem requires a LeapXRServiceProvider currently. This is something we could change to support using Desktop providers. Or in the meantime, tyou could too - by looking for just LeapServiceProvider rather than LeapXRServiceProvider [here](https://github.com/ultraleap/UnityPlugin/blob/develop/Packages/Tracking/Core/Runtime/Scripts/XRHandsSubsystem/SubsystemStarter.cs#L91)

**Comment by camnewnham** [comment]
Thanks for getting back to me Matt.

> Is there an issue with using your extended provider for your specific use-case?

Not technically. Only to a) clean up my project and b) contribute to improvements that might help others. But if (b) is not the case then no worries :)

> Also, have you considered using the [ChangeTrackingMode](https://github.com/ultraleap/UnityPlugin/blob/develop/Packages/Tracking/Core/Runtime/Scripts/LeapServiceProvider.cs#L803) function to change the tracking mode of the LeapXRServiceProvider at runtime?

Thanks - that cleans things up a little.

> you can actually just use Unity's XRHands Subsystem (follow the OpenXR tab [here](https://docs.ultraleap.com/xr-and-tabletop/xr/unity/xri-integration.html) - also highlighted in the attached image)

I'd rather use this - but I haven't managed to get it to work. I've followed the linked steps verbatim on a few occasions but I don't get any hands detected in play mode. Unity 2022.3.25f1, XR Hands 1.3.0, XRI 2.5.4, XR Plugin Management 4.4.0, Ultraleap Tracking 6.15.0, Windows 10. Running the "HandsDemoScene" as suggested.  Everything works as expected using the Leap XRHands Subsystem. "OpenXR Support" is checked in the Ultraleap Control Panel, too.

The console warns:
```
Unable to update InputActions, no Subsystem available.
UnityEngine.Debug:LogWarning (object)
Leap.Unity.InputActions.XRHandsInputActionUpdater:Startup () (at ./Library/PackageCache/com.ultraleap.tracking@6.15.0/Core/Runtime/Scripts/XRHandsSubsystem/XRHandsInputActionUpdater.cs:58)
```
```
Hand Tracking Subsystem not found or not running, can't subscribe to hand tracking status. Enable that feature in the OpenXR project settings and ensure OpenXR is enabled as the plug-in provider. This component will reattempt getting a reference to the subsystem each frame.
UnityEngine.XR.Interaction.Toolkit.Inputs.XRInputModalityManager:Update () (at ./Library/PackageCache/com.unity.xr.interaction.toolkit@2.5.4/Runtime/Inputs/XRInputModalityManager.cs:297)
```


![image](https://github.com/ultraleap/UnityPlugin/assets/19278856/45e99446-c907-414e-8318-ebcf37e78276)
![image](https://github.com/ultraleap/UnityPlugin/assets/19278856/0f1b2dbd-96d5-494e-a15c-142c45767514)
![image](https://github.com/ultraleap/UnityPlugin/assets/19278856/4ae7d2b1-cfdf-44e1-b31a-03f39081349e)
