### ISSUE TITLE
Add component for notifying the user about disabled Images

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#17]
When an app wants images but is not receiving them, we should be able to display a warning to the user warning them that the application will not function correctly until images are enabled.  Optionally, we might be able to provide some sort of interface (a button for example) to enable images for the app for the duration of the application.

**Comment by nickjbenson** [comment]
How important is it that we keep this issue around? It doesn't seem like a priority; applications that use images are few and far between, and we have changes coming down the pipeline for the image API as well. It's also been two years and I haven't seen this be a problem for anyone.

In the interest of closing issues, I vote "wont-fix" and close.

**Comment by Amarcolina** [comment]
I'd agree, I think this could be a nice-to-have at _some_ point, but we don't have an issue open for _every_ nice-to-have concept.
