### ISSUE TITLE
VRVisualizer Displaying "Desktop Mode" when using HMD's

### ISSUE THREAD

**Issue by protodeep** [leapmotion/UnityModules#172]

**Comment by testmasterbright** [comment]
So it is setting the app to desktop mode then?

**Comment by jo3w4rd** [comment]
Is this still happening? I'm not seeing it.

**Comment by testmasterbright** [comment]
Its possible it only happens on the built exe? @mmenicutch is going to take a look at it.

**Comment by testmasterbright** [comment]
We checked this and it was fixed by someone...lol. I'll include it with the Grape release.
