### ISSUE TITLE
Fix/Remove Gizmos for HandController

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#179]
The Gizmo image for HandController is just a white square right now.  We should either fix it so the icon is correct, or remove it.

**Comment by jo3w4rd** [comment]
I did a bit of investigation: The problem is that we put the image file in Assets/LeapMotion/Gizmos and it needs to be in Assets/Gizmos.

**Comment by protodeep** [comment]
This appears to be fixed @jo3w4rd @Amarcolina .  If not, ping me and I'll correct.

**Comment by Amarcolina** [comment]
It doesn't look fixed to me, I see a white square instead of an Icon
