### ISSUE TITLE
GetLeapMatrix does not belong in UnityMatrixExtension

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#25]
UnityMatrixExtension by it's name is for extension methods, which GetLeapMatrix is not.  Either we should move GetLeapMatrix to a different class, or rename UnityMatrixExtension to allow non-extension methods to make sense inside it.

**Comment by jo3w4rd** [comment]
How about 

    public static Matrix GetLeapMatrix(this Transform t) {... }

then it would be an extension, which you would use like:

    Matrix trs = this.transform.GetLeapMatrix();

**Comment by Amarcolina** [comment]
That sounds like a good solution to me.
