### ISSUE TITLE
Image Warp function may return incorrect results.

### ISSUE THREAD

**Issue by jo3w4rd** [leapmotion/UnityModules#284]
See https://community.leapmotion.com/t/orion-image-warp-in-c-giving-wrong-results/5211

**Comment by jselstad** [comment]
Does the LeapC code not match the code that is being used for the C++ plugin?

[I recall also having issues with the values that warp function was outputting a few months ago](https://community.leapmotion.com/t/rectify-function-coordinate-change/4691)

Is this a front-end team issue?

**Comment by jo3w4rd** [comment]
LeapC doesn't do the wrapping and the code in the C++ uses data that isn't, as far as I know, available from LeapC. The LeapC# code used by Unity does bilinear interpolation, so it is a different algorithm. The results should be equivalent, though not pixel-per-pixel the same.

If warping the entire image, you would want to use a shader, but for stereo-triangulating a few points per frame, warp() should work.

So yes, it is a front-end-team issue.

**Comment by jo3w4rd** [comment]
This is addressed in platform PR #6161

The warp() function used the left distortion map for both images (it was never updated when we changed to a stacked image/distortion buffer format). I also changed it so that the function took a ray input like it did in the other language bindings and added a WarpPixel function that takes a pixel coordinate.
