### ISSUE TITLE
"Can Duplicate" messes up Scene References to Hands

### ISSUE THREAD

**Issue by jselstad** [leapmotion/UnityModules#286]
Both the UI Input Module and Attachments module rely on external script references to hands.

When a hand gets duplicated and replaced in tracking, it has none of the script/scene references of its earlier counterpart.

We need an alternative to "can duplicate" where scene references are maintained; preferably a way to reassign the primary hand once a false tracked hand disappears.

**Comment by protodeep** [comment]
When a hand model is returned to the HandPool, check if it can be reassigned to any active HandRepresentation

**Comment by protodeep** [comment]
For reference:
https://drive.google.com/a/ocuspec.com/file/d/0BwY9VTf2xEyfMmdOOUxXQUgtQXM/view
