### ISSUE TITLE
Judder when moving hands in VR

### ISSUE THREAD

**Issue by jo3w4rd** [leapmotion/UnityModules#3]
See https://community.leapmotion.com/t/judder-in-vr-when-using-rigged-hands/4712

Developer reports horrible judder when using SkeletalHand-based hand models. Hand motion itself is fine, the judder occurs when the camera is moving (controlled by head tracking).

This sounds similar to the problem we had some time ago and which was fixed by parenting the hand objects to the HandController. In this earlier issue, attaching the HandController to a moving object caused the hands to judder when ever the parent object moved.

**Comment by protodeep** [comment]
Addressed with https://github.com/leapmotion/UnityModules/pull/56
