### ISSUE TITLE
Make HandPool robust to errors

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#300]
When there is any error duing init/begin/update/finish this can often result in duplicate hands as the error causes the hand pool logic to fail.  We should be robust against this and fail gracefully during all times we could be calling into user code.

**Comment by nickjbenson** [comment]
I propose we close this issue because it doesn't document a specific bug and thus isn't really definitively fixable.

Or perhaps the latest changes to the HandModelManager have addressed the issues?

@Amarcolina @protodeep

**Comment by Amarcolina** [comment]
I agree!
