### ISSUE TITLE
Investigate ways to profile time/memory on worker thread

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#32]
Currently we have no way of easily profiling performance or garbage on the worker thread, which can make it difficult to track down issues.  It would be nice to be able to have a nice process for this to be able to catch issues like #30 sooner.

**Comment by Amarcolina** [comment]
We have telemetry now!

**Comment by adrian3git** [comment]
wooo!

**Comment by ajohnston33** [comment]
wooo!
