### ISSUE TITLE
hand model can appear too thin

### ISSUE THREAD

**Issue by leapmotion-services** [leapmotion/UnityModules#359]
https://community.leapmotion.com/t/hand-model-sometimes-appears-thin/5408

Joe_WardTeam Leap Motion2h
It is a bug. I haven't narrowed down the cause yet, but I suspect that when a hand model is duplicated, the scale is not set correctly (or it be something else). As a workaround, try turning off the "Can Duplicate" option in the Hand Pool (on the LeapHandController object).

**Comment by nickjbenson** [comment]
Closing for staleness, we can re-open and investigate if it appears to still be a problem.
