### ISSUE TITLE
Unable to light candles in Attachments module example scene

### ISSUE THREAD

**Issue by mmenicutch** [leapmotion/UnityModules#363]
When using the example scene for hands module, i'm unable to light any of the candles. The smoke appears on the tip of the index finger to show that that the candle should be able to light. 

Using Core assets 4.1.3 and Attachments module 1.0.2

**Comment by jo3w4rd** [comment]
Fixed -- it was a serialization issue. Just viewing the hand attachment's child objects in the inspector fixed things.
