### ISSUE TITLE
Disabling & Enabling IEBehaviors may leave kinematics off

### ISSUE THREAD

**Issue by protodeep** [leapmotion/UnityModules#367]
Disabling and Enabling InteractionBehaviors may result in kinematics being left off.  

MobileUXTests has an earlier commit to ActivityManager.cs of code from Adrian that fixed this.  But overwrote this when merging latest UnityModules from upstream.  Poke me if that would be helpful.

**Comment by Amarcolina** [comment]
Ok we have a bunch of tests in and have fixed a bunch of state issues.  If this issue is still present we should get a specific repro case so we can add it to the tests.
