### ISSUE TITLE
Hand Pool API Improvements

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#407]
Some of the features that are possible:
- Ability to iterate over the existing pair objects
- Ability to modify the values of a pair object
- Ability to ask if a pair with a given name exists
- Zero-delay disable/enable of pairs

These features should all be available at both edit-time, and run-time, and still maintain proper state.

**Comment by nickjbenson** [comment]
Proposing we close this unless there's a compelling need for these features, in which case (at which time) we should implement them and PR them.

**Comment by Amarcolina** [comment]
I agree!
