### ISSUE TITLE
Upgrade to the latest LeapC

### ISSUE THREAD

**Issue by protodeep** [leapmotion/UnityModules#428]

**Comment by Anvil102** [comment]
This needs to run through QA first. But this needs an Android release cut of the Unity Core Assets in order for that to happen.

@protodeep @jselstad @Amarcolina to be aware of. Once a release is cut, please assign this to QA and flag it as "Ready for QA" (Looks like you'll need to add a column to your boards ;-) ).

**Comment by protodeep** [comment]
@Amarcolina @jselstad @Anvil102 This issue could be close, yes?

**Comment by Amarcolina** [comment]
Yeah I think this can be closed.
