### ISSUE TITLE
Detect Unity Version and Report Incompatibility

### ISSUE THREAD

**Issue by protodeep** [leapmotion/UnityModules#432]
Investigate detecting the version of the unity editor, preferably when installing modules, and report incompatibility.

**Comment by Amarcolina** [comment]
One way that we could accomplish this is by having modules installed by some sort of 'installer' that automatically does version checking, dependency checking, and correct file cleaning before installing.  It would be quite an endeavour but might be a good idea.

**Comment by Amarcolina** [comment]
I'm going to close this since it's right now pretty far from being possible with our current module ecosystem.  If we want to overhaul our release system, we could open up something like this again.
