### ISSUE TITLE
Include old human hand prefabs in future CoreAssets

### ISSUE THREAD

**Issue by diyamep** [leapmotion/UnityModules#456]
I am working on a project in which I have to use full human hand models, the old prefabs (PepperDarkFullRightHand, PepperMediumFullRightHand etc..) were perfect.

Unfortunately I am not able to use Autorigging scripts to convert them to Orion.
Is it possible to include them in the future release so I can use them with Orion?

**Comment by nickjbenson** [comment]
Sorry! Unfortunately, we don't have any plans to do this in the near future.
