### ISSUE TITLE
VRVisualizer window is not resizable

### ISSUE THREAD

**Issue by testmasterbright** [leapmotion/UnityModules#466]
The latest VR-Visualizer does not allow for resizing the window. It also defaults to a much smaller size on a lot of machines. 

Grape Visualizer (it launches full-screen windowed, although with 2 monitors it is not ideal but the window is resizable):
![vrvisualizer-grape](https://cloud.githubusercontent.com/assets/6034882/20906554/833a07ae-bafd-11e6-9cfa-c66cbec182be.png)

Honeydew Visualier (much smaller and cannot be resized):
![image](https://cloud.githubusercontent.com/assets/6034882/20906651/0702470e-bafe-11e6-8319-b039ccf3858b.png)

**Comment by testmasterbright** [comment]
Ok, I think I figured it out. Only new users that haven't launched VR-Viz will see the issue. I had Shaun delete the registry since he wasn't seeing it and then he got the issue. So it took the settings for him on Grape and since he didn't do a clean install he didn't see the issue.

**Comment by nickjbenson** [comment]
@testmasterbright Is this issue still relevant? I'd like to close issues that have been sitting around for a while. Happy to look into it if it's still a problem

**Comment by nickjbenson** [comment]
Looks like the current VRVisualizer does not have a resizable window. I checked a box for an incoming `develop` PR that will make UnityModules builds have resizable windows. We'll have to resolve this issue once we have a new release and we've confirmed it has resizable windows ^_^...
