### ISSUE TITLE
Get integration testing working again

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#470]
Unity 5.5 broke compatibility with the unity test tools we were using, so they have been removed and disabled for now.  We need to figure out the right way to do our testing, whether thats fix the test tools package, find another one, or make a lightweight version ourselves.

**Comment by Amarcolina** [comment]
Possibly switch to using something like this? https://www.assetstore.unity3d.com/en/#!/content/27388

**Comment by nickjbenson** [comment]
@Amarcolina We're using NUnit now, so we're good on this aren't we?

**Comment by Amarcolina** [comment]
We are good yes!
