### ISSUE TITLE
VR Visualizer does not detect Leap controller on Mac

### ISSUE THREAD

**Issue by git-shaun** [leapmotion/UnityModules#482]
When running VR Visualizer on Mac, the device is not detected.

Transferring from platform issue:
http://sf-github.leap.corp/leapmotion/platform/issues/6634

**Comment by Anvil102** [comment]
Linked issue in platform to facilitate tracking progress in a single repo: http://sf-github.leap.corp/leapmotion/platform/issues/7575

**Comment by nickjbenson** [comment]
That issue is closed as of August of last year, so I'm closing this one as well.
