### ISSUE TITLE
Leap.Finger.FingerType.TYPE_FOO simplification

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#485]
FingerType specification is repetitive. Let's replace
`Leap.Finger.FingerType.TYPE_INDEX`
with
`Leap.FingerType.Index`

To be non-breaking, let's define a new FingerType enum inside the Leap namespace and add an implicit conversion from Leap.Finger.FingerType. Then we should replace all of the UnityModules' references to Leap.Finger.FingerType with the corresponding Leap.FingerType.

Note that this will require modifying the LeapCSharp DLL.

**Comment by Amarcolina** [comment]
We unfortunately cannot define implicit enum conversions :( Csharp doesn't give us the ability to define a conversion from one enum to another.

**Comment by nickjbenson** [comment]
Rats. OK, let's just close this and when we eventually do start changing LeapCSharp maybe there'll be a better option.
