### ISSUE TITLE
Interaction Engine holding fails under locomotion

### ISSUE THREAD

**Issue by jo3w4rd** [leapmotion/UnityModules#495]
If the LMHeadMountedRig is moving too fast, interactable objects can no longer be held. Grabbing still seems to work, but the object is immediately dropped. Slowing the motion allows holding to work again -- in the example project provided by the external developer in the post linked below, the per-frame translation was set to .2 units; changing to .02 resulted in holding working again. 

See https://community.leapmotion.com/t/orion-unity-unusable-with-gameobject-movements/5896/11

**Comment by jselstad** [comment]
Try commenting out line 233 in InteractionBehaviour.cs so:
```
#if UNITY_EDITOR
      if (_contactMode == ContactMode.GRASPED && UntrackedHandCount == 0 &&
          Vector3.Distance(_solvedPosition, _warper.RigidbodyPosition) > _material.ReleaseDistance * _manager.SimulationScale ||
          Quaternion.Angle(_solvedRotation, _warper.RigidbodyRotation) > _material.ReleaseAngle) {
        _manager.ReleaseObject(this);
      }
#endif
```

becomes

```
#if UNITY_EDITOR
      if (_contactMode == ContactMode.GRASPED && UntrackedHandCount == 0 &&
          //Vector3.Distance(_solvedPosition, _warper.RigidbodyPosition) > _material.ReleaseDistance * _manager.SimulationScale ||
          Quaternion.Angle(_solvedRotation, _warper.RigidbodyRotation) > _material.ReleaseAngle) {
        _manager.ReleaseObject(this);
      }
#endif
```

**Comment by jo3w4rd** [comment]
This solves the holding part, but the object still doesn't move with the hand when grasped. I.e. you can see the blue outline turn and stay green, but the object doesn't move with the hand. If you toggle movement while holding, the block is frozen relative to the parent when movement starts, but jumps back to the hand when movement stops

Also, that code is in an editor-only ifdef, so it only affects things when playing the scene in the editor.

**Comment by Amarcolina** [comment]
So that fixes it completely for both me and jon.  Could you give specific steps to replicate the weird issue where it is grabbed but not following the hand?

**Comment by jo3w4rd** [comment]
I had made a number of changes to the hierarchy from the original project. When I went back to the original project, commenting out those lines (or running a build) work for me, too.

**Comment by jo3w4rd** [comment]
Fixed.
