### ISSUE TITLE
UIInput module Tactile mode is unusable if panel is positioned < -100 units along the z-axis

### ISSUE THREAD

**Issue by jo3w4rd** [leapmotion/UnityModules#509]
If you move the LMHeadMountedRig and the Menus objects in the example UI scene so that their z coordinates are beyond -100 units on the z axis, then UI interaction stops occurring. 

My guess is that this has to do with how the ProjectiveToTactileTransitionDistance is used. If I increase the value set from 100 to 1000, then interaction works again at -100z, but again fails beyond -1000z.

Hybrid and projective modes work, but perhaps there are other locations where these fail.

See also: https://community.leapmotion.com/t/trying-to-understand-button-functionality/5914/10

**Comment by jselstad** [comment]
Fixed with #511
