### ISSUE TITLE
Provide full-pipeline fake hand frames during edit mode

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#513]
While building things on or around hands at edit time, it's useful to be able to describe the desired positions of objects via script relative to the hands' positions. Rigged hands already create fake hand frames to represent the hands at edit time; we should standardize this: The Provider should provide and push fake frames through the entire pipeline (provider -> handController -> factory -> model) during edit time.

This would enable useful functionality like [ExecuteInEditMode] this.transform.position = Hands.Right.PalmPosition for modeling/greyboxing hand attachments. Currently the only way to do this is to drag in Attachment Hands, which is a lot of extra dragging/deletion steps if the scene otherwise does not need Attachment Hands. A change like this should probably also come in tandem with a customization option to specify different edit-time hand poses.

**Comment by Amarcolina** [comment]
One tricky part is how to get this to work not just for ServiceProvider but for all providers... 🤔

**Comment by nickjbenson** [comment]
What are the alternative providers? A networked hand provider? It might make sense not to drive fake hands for a networked hand provider, or recorded hand provider. I probably wouldn't want fake hands at edit time for a recorded hand provider; I might confuse it for a part of the recording. Are there other provider paradigms where fake hands make intuitive sense?

**Comment by Amarcolina** [comment]
One really really strong reason for edit time hands for recording playback providers is edit time animation scrubbing! :D If I am trying to build hands for a tutorial bot it would make sense to me that i would want edit-time ability to work on his hands, as well as get scrubbable playback preview of the recordings being played back.  Once the timeline sequencer gets released this will also sync really nicely with that.

**Comment by nickjbenson** [comment]
That does make sense, but that's also an entirely different way of providing hands: It has its own subclass-dependent source for the faked hand pose. But it does make sense that we should be able to push poses in general at edit time whether they're "fake" or not. LeapProvider already has an abstract CurrentFrame property. Could we simply add [ExecuteInEditMode] to LeapServiceProvider, implement the edit-time check and fake frame construction in CurrentFrame.get, and individually allow other edit mode behavior in any given implementation of LeapProvider?

**Comment by Amarcolina** [comment]
That would be the start, but we would have to put checks all over the place to make sure we are not trying to construct controllers or things like that.  Also making sure that HandController and the HandPool can also run at edit time will be non-trivial.  Not impossible, but definitely tricky

**Comment by Amarcolina** [comment]
Going to be finally addressed by #948 !!!!
