### ISSUE TITLE
Discuss and explore naming for the new gui system

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#514]
There is going to be a lot of naming conflicts while making the new gui system.  Currently Unity already has a ton of words and phrases reserved by their own gui system, like Panel, or Image :P How do we properly distinguish our components from Unity's?  Do we prefix everything with Leap?  That kinda sucks...  

To discuss!

**Comment by Amarcolina** [comment]
Also worth clarifying that since namespaces don't show up in the inspector, we cannot rely on a clear namespace to get us out of the woods entirely.  So we can't do Leap.Unity.Gui.Rendering.Panel class, because then it will just show up in the inspector as Panel :( which already exists.

**Comment by nickjbenson** [comment]
What if we had custom icons for each element that clearly distinguished it as within the Leap namespace? That could act as our "Leap" prefix without needing to actually have that prefix.

Still, having a unique name might just be better.LuiPanel LeaPanel LePanel VuiPanel LeapPanel LPanel LElement LelPanel

**Comment by protodeep** [comment]
I second what Nick said.  Both things would be good.  We discussed Leap icons for Leap monobehaviors.  And some prefix to differentiate from Unity gui classes seems good.  Certainly have seen that approach in some of the more complex Unity assets I've used over the years.

**Comment by Amarcolina** [comment]
Unity gui elements all have a kind of yellow tint in their design, and are all 2d (makes sense for a 2d gui system).  What would you guys say to choosing a contrasting color theme (leap green/black maybe?), and using 3d styled icons instead of 2d to emphasize that the new gui system works in 3d instead of 2d? 

![unityguiicons](https://cloud.githubusercontent.com/assets/5723312/22268719/601bcdae-e23d-11e6-9913-51cbb33933d4.jpg)

**Comment by Amarcolina** [comment]
Also worth noting that Unity uses a grey color scheme instead of yellow for layout components.  I think it would definitely be great to follow the same idea of different categories of components being in different styles.

![unityguiicons](https://cloud.githubusercontent.com/assets/5723312/22268884/125e6210-e23e-11e6-95e2-201483f280e6.jpg)
