### ISSUE TITLE
Allow user to change max element count without editing shader class

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#518]
Currently the maximum number of elements in a gui is specified in the cginc file.  If the user wants to increase the limit they will need to open this shader file and modify the value directly.  It would be nice if there was a better way to go about this, possibly with codegen???

**Comment by nickjbenson** [comment]
Ehhhh... Opening a .cginc and changing one variable isn't thaaat hard. Even if you've never opened a .cginc in your life, it's not too hard to change a number, IF you hit the limit and see an Error pop up describing the problem and what variable to change.

**Comment by Amarcolina** [comment]
Unfortunately there is no way to know what the current max limit is on the script side :( So we cannot throw an intelligent error.

**Comment by nickjbenson** [comment]
So we can't even know if we've hit the limit?

**Comment by Amarcolina** [comment]
Ah, yeah that's a better way to put it, we cannot throw an error currently lol.  The limit is defined *only* by that single line in the cginc.  I don't believe there is any way to figure out what that limit is without actually opening the file and parsing it.

**Comment by Amarcolina** [comment]
```
mat.SetFloatArray("_MyArray", new float[128]);
print(mat.GetFloatArray("_MyArray").Length);
```
When the material is using a shader with an array of size 5, this will still print out 128 :(

**Comment by nickjbenson** [comment]
Well, that's definitely an accessibility problem. The options I see are 1) codegen the file from, like, bluh.cginc.template, apply and enable an error popup by tracking the value set in a manager component, or 2) automatically raise an intelligent error by opening the cginc and applying a simple regex. I am kiiind of OK with option two; maybe we provide a comment in the .cginc saying "Hey careful with this variable name! There is magic here, see LeapGuiManager.cs". Option one seems like a pain just to get one variable value.

**Comment by Amarcolina** [comment]
I too like option 2.  There might be a compromise option 3 that would be simple-ish.  If we are already loading the file and using a regex to validate the current max element size, we could easily open it for write in addition to read and just modify the file directly XD We already used the regex to find the part in the file where the value is located anyway, so might as well write it back out again.

**Comment by nickjbenson** [comment]
Yeah, I like that idea. If the regex fails to find a match we can also raise an error saying "Hey!! You touched the cginc and it's bad man! Fix me!"
