### ISSUE TITLE
Rescan and merge subtle IE fixes into the revised system for robustness.

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#534]
The Interaction Engine has had a lot of work put into it over the past six months or so, and in that time it's earned various fixes that address stability in subtle edge-cases. Since we're removing external dependencies and a big architectural shift towards the unified interaction system, we need to make sure we don't lose the maturity of the current IE in the process.

One example of this is the "misbehaving object" logic in the original ActivityManager that marks objects that have exploded for no reason (because blah blah physics is unstable sometimes). That helped alleviate the symptoms of rare bugs in the original IE that would cause explosive behavior. The new system should track this too. Ideally we would preserve feature-parity for even the little things like this.

**Comment by nickjbenson** [comment]
Marked as highly complex due not only to the review process required but also testing infrastructure we should utilize to actually make sure the revised IE isn't buggier than the current IE. (Maybe pie-in-the-sky, but you gotta have goals.)

**Comment by Amarcolina** [comment]
Yeah I definitely want to get our testing infrastructure back to a working state, that will be super valuable in making sure things are solid.  Unity broke their asset last time I checked but it shouldn't be too hard to implement a lightweight version ourselves

**Comment by nickjbenson** [comment]
This has had a chance to sit for a while, so I'm pretty confident we either have the stability of the old engine or we have known issues being addressed in ticket form or PR form.
