### ISSUE TITLE
Make decision about HandFactory/HandRepresentation

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#549]
Currently HandRepresentation holds a reference to HandPool, which breaks the HandFactory/HandRepresentation abstraction.  Either we need to correctly implement the abstraction, or get rid of it completely.

I am in favor of getting rid of the abstraction, such that we ONLY have HandPool and HandProxy (we can rename HandProxy if we don't like it) and getting rid of HandFactory and HandRepresentation.  They are part of an abstraction that has never been used, even in all of our complex Leap Motion Shenanigans™.  Furthermore, we don't even follow the abstraction right now because it was getting in the way of implementing new features that were actually useful.

**Comment by nickjbenson** [comment]
As someone who did not write any of this I'm all for it! :P

With the latest stuff we're working on, I think we're gearing up to a large breaking change in UnityModules anyway. With the DevX initiative being a recent focus as well, I think it's in general a really good time to make big changes like this, if it helps simplify and/or streamline any mental gymnastics a developer has to do when they poke around our internals.

Curious about @protodeep 's thoughts, being more familiar with the shaping of this stuff originally. (And @jo3w4rd ?) I personally think that any situation where an interface only has one implementation (as is the case for HandRepresentation/HandProxy) iiiis suspicious.

Also, good issue, highly watermelon 🍉 🍉 🍉

**Comment by protodeep** [comment]
I'm not opposed, since, indeed, we've never found the need for another type of HandRepresentation and extra clarity bits are worthwhile.  I think we would need to do this carefully, with some thorough QA testing since its in a central spot.  

Even innocuous stuff, like the fact that changing members would likely break a lot of references within scenes and prefabs, we have to be mindful of the other work it'll incur.  Not just in UnityModules but all our other ongoing projects.

**Comment by Amarcolina** [comment]
Luckily HandRepresentation is a runtime class, so we wouldn't run into any prefab/serialization issues if we removed it.  HandFactory doesn't contain any member variables either, so removing it wouldn't lead us into any weird prefab corruption issues either.  

I agree that we should definitely do this carefully, probably in it's own PR as nick suggested so we can isolate the change and get some great QA on it.
