### ISSUE TITLE
Provide proper Contact checking/callbacks in Revised IE

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#566]
Currently the revised IE does a quick-and-dirty index fingertip check to provide contact callbacks.  This should be replaced with proper checks for collision with the whole hand.

In all likelihood this means bringing BrushHands in from the original IE or merging their functionality with InteractionHands. This should be done after the penetration-hands branch is merged into the current IE.

Care should be taken that Contact callbacks are robust to motion of the player rig (currently some spaceship velocities make buttons unreliable -- need debug drawing to check).

**Comment by ajohnston33** [comment]
I thought Unity already provided contact callbacks for brush hands.

**Comment by nickjbenson** [comment]
It does. OnCollisionEnter/Stay/Exit are totally valid options if (at this point, when) BrushHands are incorporated into the revised IE. On(Object)ContactBegin/Stay/Exit will provide Hand objects as callback arguments, and represent a more convenient interface for getting useful interaction behavior more directly and 'purely' specified for interaction objects relative to interacting hands.
