### ISSUE TITLE
Revised IE: Re-implement RigidbodyWarping

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#569]
When an interaction object is held, we must modify its visual position based on the motion of the hands to reduce perceived interaction latency. It's just a consequence of the separate physics timestep. The RigidbodyWarper class already exists from the old IE and InteractionBehaviours in the revised IE have and initialize their RigidbodyWarper references, but they simply don't do anything with them.

**Comment by nickjbenson** [comment]
Since we made the change to fix interpolation/extrapolation for physics hands, I don't think this is an issue anymore for us. We've gone a long while without rigidbody warping and haven't seen it come up as an issue for sure, so I think it's best to drop both the unused checkbox on InteractionBehaviours and archive the script somewhere since it's not being used anyway.

New task to close this issue:
- [ ] Make a PR that removes the RigidboyWarping script and the associated checkbox from Interaction Behaviours.

**Comment by Amarcolina** [comment]
I agree for sure!  Not to mention the solution we have right now is a lot better than the old hack...

**Comment by nickjbenson** [comment]
PR coming in soon. Closing.
