### ISSUE TITLE
Revised IE: Support PivotAroundOrigin in Kabsch solver

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#572]
Kabsch works for normal grasping behaviour but PivotAroundOrigin is broken. Either fix it or establish a different way of supporting pivoting UI elements like joysticks and levers. (Will be addressed in at least one of the example scenes.)

**Comment by ajohnston33** [comment]
This is a general problem for the IE.  I wanted a general solution, instead of one with endless one offs and a fragile authoring workflow.  

Also see:  "Manipulating large constrained objects: Large steering wheel. Bike handlebars."  Under http://sf-github.leap.corp/leapmotion/platform/issues/6079

**Comment by nickjbenson** [comment]
Definitely don't have a robust solution for what you're describing there, but at the very least we've got the original PivotAroundOrigin implemented. There's also an auto-detect on InteractionBehaviours for checking PhysX body/joints to pick PivotAroundOrigin in the InteractionBehaviour has its position locked. This is good to start testing with so we'll revisit the general solution later.
