### ISSUE TITLE
Issues in Leap.Hand.Basis and Leap.Hand.TransformedCopy

### ISSUE THREAD

**Issue by cherullo** [leapmotion/UnityModules#6]
There are two issues in this method:
```
//TODO verify this calculation for both hands
_basis.zBasis = -Direction;
_basis.yBasis = -PalmNormal;
_basis.xBasis = _basis.zBasis.Cross(_basis.yBasis);
```
The first is that, as the comment present in code suggests, the cross product must be different for each hand, if a left-handed basis is expected for left hands, and a right-handed basis is expected for right hands.
The second is *much* more subtle. When you call the method Hand.TransformedCopy, a new Hand instance is created where the vectors Direction and PalmNormal are multiplied by a matrix, usually the LeapMatrix. Now, the LeapMatrix _M_, as currently provided by the method Controller.GetLeapMatrix, has a reflection on the Z axis, and thus we have that: 

_M_(-Direction x -PalmNormal) != _M_(-Direction) x _M_(-PalmNormal)

Which is to say that  the value of Hand.TransformedCopy(...).Basis.xBasis is wrong.

The following snippet illustrates the issue:
```
      Matrix leapMat = GetLeapMatrix();
      Frame frame = leap_controller_.Frame(); 
      Frame transformed = frame.TransformedCopy( leapMat );

      if (frame.Hands.Count > 0)
      {
          Assert.AreEqual(
              // _M_(-Direction x -PalmNormal)
              leapMat.TransformDirection(frame.Hands[0].Basis.xBasis).Normalized,

              // _M_(-Direction) x _M_(-PalmNormal)
              transformed.Hands[0].Basis.xBasis
              );
      }

```
The assertion always fails.

**Comment by jo3w4rd** [comment]
This has been fixed by the change to use Quaternions and the change to use a consistent basis type for both hands -- always right-handed.
