### ISSUE TITLE
Overhaul Runtime Gizmos

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#612]
Runtime gizmos are becoming more and more important as we continue developing in VR, especially as we delve into mobile vr where visualization is even more important for debugging and understanding.  The system could be improved in a number of ways:

Optimization:
 - Prebuild meshes for all default shapes (capsules / cubes / spheres)  Many of these are there already, but we should have full coverage.
 - Custom vertex shaders for the tricky shapes like capsules to allow us to use a single capsule mesh for all capsule shapes.
 - Dynamically combine lines into mesh objects at draw time to reduce draw-call overhead.
 - Additional apis to allow faster expressing of existing concepts (like an api to draw a multi-segment line, much faster than drawing a bunch of individual lines)

Workflow Improvements:
 - Allow runtime gizmos to be used with even less setup.  
 - 1 line of code as opposed to multiple
 - No need to create the runtime gizmo manager 

Cool features:
 - Allow scene picking!  Really sucks that we don't have this
 - Allow gizmos to be turned on/off on a per-type basis??

**Comment by nickjbenson** [comment]
Migrated to https://github.com/leapmotion/UnityModules/wiki/Feature-Wishlist
