### ISSUE TITLE
Create Init funcitons for every component

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#639]
Currently a lot of our scripts (probably most of them!) require serialization in order to receive their values/settings.  This makes it difficult/impossible to add them at runtime with AddComponent and have them work properly, because there is no way to initialize them!

We should add an Init function (or a similar concept) to all of our scripts so that developers can use AddComponent without breaking things!

One challenge is that the Awake is called from within AddComponent, making it tricky to give the object it's settings before it is already trying to do initialization within awake.  We would have to write all of our components under the assumption that it is 100% ok for the settings to be incomplete within awake, and that at any time after Awake you could expect a call to Init.  We could enforce some rules to make things easier/more consistent.  Things like Init would have to be called before OnEnable/Start, and could only be called once, but we will have to see!

**Comment by nickjbenson** [comment]
Workaround: Awake() isn't called unless the GameObject is active, so a developer could feasibly do `AddComponent` on an _inactive_ GameObject and then activate it after they've set its serialized properties.

**Comment by nickjbenson** [comment]
@Amarcolina recommending close, and we can open new issues per-bug if we start experiencing issues with component initialization.

**Comment by Amarcolina** [comment]
yeah i agree, we shall close for now
