### ISSUE TITLE
Slider ranges could be configured in local scale instead of world scale

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#662]
Currently slider ranges are configured in world distance instead of local distance, which can make it difficult to figure out how to tune the slide range correctly when you are deep down in a hierarchy that is not at world scale.  Furthermore this makes a slider behave differently when it's parent is scaled up or down, which I think is unintuitive.

**Comment by jselstad** [comment]
Ah, fixed this a while ago
