### ISSUE TITLE
Automatically watch for incorrect movement for IE

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#736]
Might be possible (and a good idea) to have a script dedicated to seeing if the user actually moves their camera rig at the correct time to allow proper IE response and throw an error/warning to the console if it is done incorrectly.  It's one of those things that you don't need an API to do, and so it would be very easy for someone to make a mistake.  Could also disable the script for builds so it doesn't eat performance.

**Comment by nickjbenson** [comment]
I agree that this is a good idea, but if we have an explicit movement example (which there is now a PR for), that might be enough to clarify the correct process. Between that and the wiki section, we may have enough "bang for the buck" already to make moving reference frames make sense, and the extra state required to implement this is a little annoying (even if it's edit-time-only).

I'm going to move this to the backlog with the intention of pegging it as a IE v1.2 feature if users still have troubles with moving reference frames, but I'm open to re-prioritizing this for v1.1 again if we disagree.

**Comment by nickjbenson** [comment]
Going to close this because I haven't heard about any moving-reference-frame issues since we've had the example added.

**Comment by Amarcolina** [comment]
Yeahh it's hard.  I _did_ run into this issue with the desktop panels, where when they are moved around the buttons would press themselves.  But I'm unsure if such a safeguard is even _possible_...
