### ISSUE TITLE
IE: Provide a moving-reference-frame + UI example

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#740]
We support moving reference frames + UI when the Interaction Manager is a child of the Transform providing the moving reference frame and the moving reference frame is moving during FixedUpdate. However, we should provide an example of this in the IE itself.

**Comment by Amarcolina** [comment]
Should definitely create a section on the wiki that lists all the rules you need to follow as well.

**Comment by nickjbenson** [comment]
Update: A work-in-progress (but functional) example scene demonstrating moving reference frames can be found in the `example-moving-reference-frames` branch.

Tasks remaining:
- [ ] Remove the starfield and add another linear-movement reference object
- [ ] Simplify the Spaceship.cs model so that it doesn't feel as complicated to support this
