### ISSUE TITLE
Allow creation of 1D sliders without collapsing rect transform

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#766]
Currently sliders look at the rect transform of their parent and decide their horizontal and vertical slide ranges based on the dimensions of that rect transform.  This means that if one wants to create something like a horizontal slider, they need to collapse the parent rect transform to have no height.  This means that the slider itself cannot inherit any height related attributes from it's parent, making it impossible to have things like buttons or text boxes that correctly adjust their heights based on the parent panel height.

We should investigate the best way to get around this issue.  One way might be to bite the bullet and make it so that you need to explicitly set up your slider as either a horizontal, a vertical, or a two dimensional slider.  We could also potentially clean up some of the inspector by hiding / renaming properties based on the mode of the slider as well.

**Comment by nickjbenson** [comment]
Addressed by #773
