### ISSUE TITLE
Explore more physical feedback for integer sliders

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#769]
Currently notched sliders snap instantly to their new positions, it would be really nice to have some sort of graphical/physical effect that made things more natural.  We could explore a couple of different options.

**Comment by nickjbenson** [comment]
At this point I tend to just round the slider value I return as a post-process when I feed the value into whatever the slider is controlling. The only thing missing from this is something like having the slider snap into the rounded value's position when the user stop interacting with it.

This is probably the easiest strategy.

**Comment by nickjbenson** [comment]
Closing as wontfix.
