### ISSUE TITLE
how to share the project done in unity with leap motion sensor to end users?

### ISSUE THREAD

**Issue by aishu5** [leapmotion/UnityModules#770]
I'm doing a project using leap motion sensor. It works only if it is connected to pc. If I want to share my project with end users how can I share ?if my end user build it as WebGL in their pc using cloud build and connects leap will it work? or is there any other way? to do this

**Comment by Amarcolina** [comment]
The only supported build platform right now is a Windows standalone build.  WebGL is not supported currently, and there are no plans in the works to support it AFAIK.  If you _do_ build a windows standalone build, your users should be able to access leap motion data easily as long as they have the leap device plugged into their computer and have the correct leap runtime installed and running.

**Comment by aishu5** [comment]
Thank you so much for replying !! I am doing a project using leap motion to
assemble a model of a product using unity. I tried searching tutorials
based on this  but I don't get any thing. Can you suggest me any GitHub
profile or tutorials as reference of how to do it please do reply.

**Comment by Amarcolina** [comment]
It depends on exactly what you are trying to do.  Can you explain in more detail what you are trying to accomplish ?

**Comment by aishu5** [comment]
https://m.youtube.com/watch?v=oKqtkBfPB3k

I want to build something like the above link.  By using leap the user has
to assemble things and also able to disassemble it.

**Comment by Amarcolina** [comment]
In terms of how to grab and move pieces around, you can use our [Interaction Engine](https://github.com/leapmotion/UnityModules/wiki/Interaction-Engine) to accomplish this.  

In terms of how to actually have pieces snap together and build a model, that is unfortunately a little out of the scope of working with the leap, as it is just a regular problem that you might run into while making a game/demo.  I don't have any tutorials on-hand that could help with such a task unfortunately.

**Comment by aishu5** [comment]
Yea! Okei thank  you!  One more last doubt. Actually customer wants the
project in vr. If I share the project as standalone aNd they connect leap
in their system. Ter is a option in leap to connect it to mobile and put
the phone inside Google cardboard. Can you explain how to do this? Because
they want the application in vr with leap.

On 06-Jul-2017 2:17 am, "Alex Marcolina" <notifications@github.com> wrote:

In terms of how to grab and move pieces around, you can use our Interaction
Engine <https://github.com/leapmotion/UnityModules/wiki/Interaction-Engine>
to accomplish this.

In terms of how to actually have pieces snap together and build a model,
that is unfortunately a little out of the scope of working with the leap,
as it is just a regular problem that you might run into while making a
game/demo. I don't have any tutorials on-hand that could help with such a
task unfortunately.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/leapmotion/UnityModules/issues/770#issuecomment-313222145>,
or mute the thread

**Comment by Amarcolina** [comment]
The only VR modes that are currently supported are PC based vr devices, such as the Oculus or the Vive.  Cardboard and other mobile devices do not have VR supported for the Leap Motion right now.

**Comment by nickjbenson** [comment]
Closing. This isn't really the place for project advice; I would recommend checking out the communty site https://community.leapmotion.com/c/development instead.
