### ISSUE TITLE
IE: Null reference exception with inactive Compound (Mesh) Collider

### ISSUE THREAD

**Issue by julienkay** [leapmotion/UnityModules#801]
When using Compound Colliders where one child collider is a MeshCollider and its GameObject is disabled, collider.attachedRigidbody returns null, therefore causing a null reference exception when used in InteractionBehaviour.GetHoverDistance() -> ClosestPoint().

I attached a prefab with an object set up in that way:
[CompoundColliderTest.zip](https://github.com/leapmotion/UnityModules/files/1176208/CompoundColliderTest.zip)

On a related note: When using a non-convex MeshCollider the native Physics.ClosestPoint() is used and throws the Warning: 'Physics.ClosestPoint can only be used with a BoxCollider, SphereCollider, CapsuleCollider and a convex MeshCollider.'
I know non-convex MeshColliders are generally bad performance-wise and can only be used with kinematic RigidBodies anyway, but interacting with such a configuration (non-convex MeshCollider + kinematic Rigidbody) works fine. Is there functionality that breaks when GetHoverDistance() throws that warning and if no how can I get rid of it?

**Comment by nickjbenson** [comment]
Thanks Julien, I'll take a look at the prefab soon.

Regarding mesh concavity support:

Supporting non-convex MeshColliders is really a thing Unity elected not to do when they rejected them for Physics.ClosestPoint support. In truth, they did this for the same reason we don't support non-convex MeshColliders: Getting the closest point to a non-convex mesh surface is really non-trivial to accelerate and make practical.

GetHoverDistance(), contrary to its name (my fault), is actually generally used for distance information relative to an InteractionBehaviour and not _only_ for hover. It's one of the critical components of an Interaction Behaviour that allows the Interaction Engine to function.

I don't think it makes sense for us to support non-convex mesh colliders right now. I'd recommend use proxy collision geometry instead (using multiple collision primitives to approximate your concave mesh) -- it's grunt-work, but it'll also run faster in the end.

**Comment by nickjbenson** [comment]
Added a fix to the upcoming IE v1.1 PR. Deactivated-object colliders on initialization of an interaction object are now ignored when the object initializes its colliders. If you need the fix now, check out these two commits, which address this issue:
(1) Ignore inactive colliders when initializing intObj colliders: https://github.com/leapmotion/UnityModules/commit/db494222c3e6298b9c0963e15e56f8542d1e633e
(2) Refresh collider layers when adding new ones at runtime: https://github.com/leapmotion/UnityModules/commit/0daf95ff4e9c99306656422a71f41bdf1c0991c4


Note that when you _activate_ the new collider's GameObject, you will have to then call RefreshInteractionColliders() so the engine can do the appropriate book-keeping. Testing this also resulted in a fix where the added collider wasn't getting its object layer set appropriately, so overall, adding colliders at runtime should work just fine as long as you call RefreshInteractionColliders().

There is a small issue where, once an object is grasped via a certain collider, deactivating that collider's GameObject won't release the grasp. This is also not cause any errors, but it's definitely not correct behavior. I'm going to add that as a new bug ticket, but the fix involves adding some more book-keeping that's probably not critical for IE 1.1.
