### ISSUE TITLE
Crash in LeapCSharp.NET3.5.dll file related to native code interop

### ISSUE THREAD

**Issue by mmozeiko** [leapmotion/UnityModules#821]
`LeapInternal.Connection.GetInterpolatedLeftRightTransform` method has following code:

    // event.pHands is IntPtr
    int num = event.pHands.ToInt32();
    int num2 = num + Connection._handIdOffset;
    int num3 = num + Connection._handPositionOffset;
    int num4 = num + Connection._handOrientationOffset;
    ...
    int num5 = Marshal.ReadInt32(new IntPtr(num2));

The variable names might be different, because I'm using decompiler to see the code.

In project I was working this makes Unity Editor to crash almost all the time when I'm running the game and there is at least one hand visible. This happens because in 64-bit mode IntPtr is 64-bit value. Converting it to 32-bit loses upper 32-bits. So when Marshal.ReadInt32 is called, it will try to access invalid memory address and mono will crash in native code.

When I changed code to following, then everything works as expected, no more crashes:

    long num = event.pHands.ToInt64();
    long num2 = num + Connection._handIdOffset;
    long num3 = num + Connection._handPositionOffset;
    long num4 = num + Connection._handOrientationOffset;
    ...
    int num5 = Marshal.ReadInt32(new IntPtr(num2));

long type allows to store 64-bits, so this code will work correctly for 32-bit and 64-bit platforms.

This is on Windows with Unity 5.6.0f3.

**Comment by Amarcolina** [comment]
Wow this is a really great catch!  One wonders how it managed to function at all...  Thank you so much for the report, will get on this right away and make sure everything is upgraded to 64bit pointers instead of 32bit.

**Comment by Amarcolina** [comment]
Ok update on this issue, we have fixed it in our internal repo for the LeapCSharp dll, the fix should make its way out once the next release of UnityModules goes out.  If you absolutely need a new version of the DLL (sounds like you already made a new one!) let me know and I can see if I can make one!

I'm going to keep this issue open until the release goes out.

**Comment by AntEduard** [comment]
Hey, 
I suffer the same poblem. Is there a chance to get the new DLL? Or could you make a guess for the release day?

**Comment by Amarcolina** [comment]
I'm trying to push out a hotfix release asap, so stay tuned!

**Comment by Amarcolina** [comment]
Also @mmozeiko I can't thank you enough for tracking down the source of this bug.  For whatever reason none of us here can reproduce it, I can't imagine how long this bug would have gone undiagnosed without your help.

**Comment by mmozeiko** [comment]
Yeah, this bug was very weird. Took me a while to figure out. It did not happen when our scene was empty with few objects. Then everything worked. It started to crash only when we imported huge terrain. I guess memory layout changed and mono/windows started to allocate on more than 32-bit address space. In any case very strange, I kind of expected it to randomly allocate in whole 64-bit process address space in any situation. I did not investigate more because reason for crash is pretty obvious.

Btw, any reason why source for LeapCSharp managed dll file is not public?

**Comment by nickjbenson** [comment]
The source for LeapCSharp is in one of our internal repos because we have integration testing set up for it that ensures it always interops properly with our LeapC API. We've talked about having the source publicly available -- and in the past, it was public IIRC.

We have plans for some optimizations to implement in LeapCSharp, so we can revisit the idea of making it public once more when we get to that on our roadmap. Obviously it helps making this sort of thing easier for our developers to address in the future, and that's one reason we weren't really considering before. Would help to know how strongly our developers would desire this overall.

**Comment by testmasterbright** [comment]
@mmozeiko @AntEduard can one of you share your project with us? I am the QA manager here at Leap Motion and I want to ensure that we have a repro case in house to test against. Your help would be greatly appreciated.

**Comment by mmozeiko** [comment]
I can share Unity project that crashes for us. I'll prepare it and will send it to the e-mail.

**Comment by testmasterbright** [comment]
@mmozeiko Thank you!

**Comment by testmasterbright** [comment]
@mmozeiko We have a new package we would love for you to try. In lieu of sending your project to us, can you please let us know if this addresses the issue? Thank you so much!

[CoreAssetsRelease4.3.2-prerelease.zip](https://github.com/leapmotion/UnityModules/files/1301155/CoreAssetsRelease4.3.2-prerelease.zip)

**Comment by AntEduard** [comment]
I just tested the prelease and it works for us now!
@mmozeiko Poorly, I can't share the project with you and when I tried to substitude the assets I am not allowed to share, the error didn't occur. We also work with highly detailed models.

Thanks to all of you guys!

**Comment by Amarcolina** [comment]
Alright everybody, release is going out today, thank you all for your help!  If anybody sees this issue again, feel free to re-open this issue.
