### ISSUE TITLE
BitConverterNoAlloc unsafe code optimization

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#825]
Currently BitConverterNoAlloc uses some union tricks to get around allocating memory.  Looking at the assembly generated this is actually not the most efficient thing in the world.  After running some tests I can get things to be much faster when using unsafe code.  Currently unity doesn't allow this naively, but it will soon!  Would be a good opportunity to do this upgrade!

**Comment by jselstad** [comment]
Optimization merged!
https://github.com/leapmotion/UnityModules/pull/913
