### ISSUE TITLE
Null reference exception when disabling InteractionButton in OnPress() Callback

### ISSUE THREAD

**Issue by julienkay** [leapmotion/UnityModules#836]
When the GameObject of the InteractionButton that is pressed gets disabled through a script, access to the _lockedInteractingController in InteractionButton.OnDisable() throws a NullReferenceException. A null check fixes this.

**Comment by julienkay** [comment]
Upon further investigation a null check is not enough, since I can't interact with any InteractionButtons anymore afterwards, possibly because the primaryHoverLocked is never set to false but I'm not sure.

I have a (very ugly) workaround, so no need for a fast fix.

**Comment by Amarcolina** [comment]
Thanks for the report!  Could you post the null reference that you received?  Sounds like a null check could be the right solution to that issue but it would be helpful to properly diagnose the issue.

**Comment by Amarcolina** [comment]
ah my mistake you already said there it was, right there, in the first post 😆 looking into things now :)

**Comment by julien-r3dt** [comment]
Sure, no problem. I looked into it a bit more and attached my changes here in case it helps. I added some more null checks in the Update() method. Also, I'm not sure if all the changes I made in OnDisable() are strictly necessary, but everything seems to be working.

[InteractionButton.zip](https://github.com/leapmotion/UnityModules/files/1282969/InteractionButton.zip)

**Comment by nickjbenson** [comment]
I'll add this to the next IE milestone! I've seen some issues with the controller locking as well.

**Comment by nickjbenson** [comment]
This was fixed in a PR and `develop` has test cases for this, so it should no longer be an issue.
