### ISSUE TITLE
NullReference Exception when Instantiating a GraphicRenderer using a TextGraphic at runtime.

### ISSUE THREAD

**Issue by julienkay** [leapmotion/UnityModules#875]
This is the error I'm getting:
NullReferenceException: Object reference not set to an instance of an object
Leap.Unity.GraphicalRenderer.LeapTextRenderer.generateTextMesh (Int32 index, Leap.Unity.GraphicalRenderer.LeapTextGraphic graphic, UnityEngine.Mesh mesh) (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/RenderingMethods/LeapTextRenderer.cs:271)
Leap.Unity.GraphicalRenderer.LeapTextRenderer.OnUpdateRenderer () (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/RenderingMethods/LeapTextRenderer.cs:98)
Leap.Unity.GraphicalRenderer.LeapGraphicGroup.UpdateRenderer () (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/LeapGraphicGroup.cs:328)
Leap.Unity.GraphicalRenderer.LeapGraphicRenderer.doLateUpdateRuntime () (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/LeapGraphicRenderer.cs:216)
Leap.Unity.GraphicalRenderer.LeapGraphicRenderer.LateUpdate () (at Assets/LeapMotion/Modules/GraphicRenderer/Scripts/LeapGraphicRenderer.cs:194)

Steps to reproduce:
- Open one of the example scenes (e.g. Curved Space Examples)
- Create a prefab of a Renderer that renders at least one TextGraphic (e.g. Renderer (1))
- Write a simple script that instantiates this prefab.

I tested this with the current develop branch (commit 0ec9abc01c58de8859ad262c582ee333e5007ac8)

**Comment by nickjbenson** [comment]
This would be @Amarcolina's territory, but in general with a Graphic Renderer, since it has to bake mesh data ahead of time in order to provide its benefits, the general strategy is always to have _all_ the GRs you need at edit-time and simply enable / disable them at runtime.

It may be possible to support manually instantiating GRs at runtime in the future, but since this would have a _hefty_ frametime cost, it's currently unsupported.

**Comment by nickjbenson** [comment]
The discoverability for this isn't so great though. I wonder if we can add a clear error message that says something like "Did you attempt to instantiate a Graphic Renderer at runtime?"

**Comment by Amarcolina** [comment]
This should be fully supported, so definitely a bug of some sort, I'll take a look!

**Comment by Amarcolina** [comment]
Ahh actually that's right, there was the change made for the GR to store it's assets in the scene file, not as assets on disk.  This means that both meshes, atlased textures, and materials become null in a prefab.  The materials can be reconstructed for cheap (meshes too for dynamic renderers and text renderers) but the atlased textures cannot unfortunately.

So this basically means that prefab support for _Graphic Renderers_ is basically unsupported at this time.  Note that making prefabs of _Graphics_ should still be completely supported.

Agree that this needs to be 100% discoverable, I'll open a new ticket that discusses ways to make sure it is obvious that spawning graphic renderers at runtime is not currently supported.

**Comment by Amarcolina** [comment]
Opened ticket #876

**Comment by julienkay** [comment]
I understand. If this can't be easily fixed I guess we can close this issue.

**Comment by Amarcolina** [comment]
Alright, i will close this, sorry for the inconvenience!
