### ISSUE TITLE
Interaction controller (hand) gets stuck in soft contact state 

### ISSUE THREAD

**Issue by AntEduard** [leapmotion/UnityModules#896]
Hi, 
as mentioned in this [thread](https://community.leapmotion.com/t/unity-interacition-hands-stuck-in-soft-contanct-state/6519) the interaction hand gets stuck in soft contact state, when the hand is inside an interactive object and the tracking is lost (e.g. due to simply looking away). I attached the minimal Unity project setup. 
- Open Minimal scene and start (debug controller gizmos are enabled)
- Rotate the object with your hand tracked by leap motion 
- You will see it keeps the soft contact mode while staying inside the object
- Keep your hand inside the object and look away 
- Now the hand is stuck in soft contact state

[SoftContactBugMinimal.zip](https://github.com/leapmotion/UnityModules/files/1394049/SoftContactBugMinimal.zip)

**Comment by nickjbenson** [comment]
We've been able to reproduce so I'll add this to our backlog for 1.2. If I'm able to find a quick fix, I'll respond here with it so you can copy/paste a patch in.

Thanks for the report!

**Comment by AntEduard** [comment]
I also made another observation on this issue.
If the hands gets contact again with the very same object, when the tracking was lost, the hands state toggles again as it should. 
Maybe it is a subscribe/unsubscribe thing. I hope it helps!

**Comment by AntEduard** [comment]
Any updates?

**Comment by nickjbenson** [comment]
Finally got to this issue. Fix wound up being pretty simple once I was able to figure out what was going on. Thanks for the example scene! It's a one-line fix so check out the diff in the PR and feel free to copy-paste the solution into your project if you need the fix now; this PR is targeted for `develop` so it won't be public until our next IE release.

https://github.com/leapmotion/UnityModules/pull/906
