### ISSUE TITLE
Disabling Images Reduces FPS to 50

### ISSUE THREAD

**Issue by DavidSHolz** [leapmotion/UnityModules#9]
If you disable images via control panel or in Unity it reduces the core assets fps to 50 and produces weird judder artifacts.

**Comment by jo3w4rd** [comment]
LeapImageRetriever needs to be smarter. Right now it is waiting for images even if they are never going to arrive. When images are turned off it waits the entire 9ms, which limits the frame rate.

There is no longer an image policy flag. We will have to check the Config setting for "images_enabled" directly. There is a proposal that LeapC broadcast config setting changes. That would help here.
