### ISSUE TITLE
Disabling an InteractionButton OnPress doesn't release the interaction lock with it

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#900]
QA encountered a bug where the "Ready" button in our particles User Test app was unpressable by the hand that hits the "Next" button just before it appears.

Investigating the issue with Caleb, I found that the interaction lock on the hand that presses the last "Next" button doesn't get released when the button disappears and the "Ready" button appears.

- [ ] Confirm that disabling an InteractionButton (or destroying?) just after pressing it causes this issue
- [ ] Fiiiix it

**Comment by Amarcolina** [comment]
We should also add an integration test since this is the second time this ticket has been filed.  Original is #664.

**Comment by nickjbenson** [comment]
Yep, already got the test scene open so I can make a recording for pressing a button.
