### ISSUE TITLE
The SingleLayer enum list dropdown doesn't show layers beyond User Layer 14

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#912]
Ran into a strange issue where Barrett was trying to add something like a sixth user layer and the layer dropdown for Interaction Overrides simply wasn't showing it.

**Comment by Amarcolina** [comment]
Interesting, I cannot replicate this, all layers always show for me.

**Comment by nickjbenson** [comment]
If I can't replicate it I may try to test it in the Scaffolding project, because I watched it happening in that project.

**Comment by nickjbenson** [comment]
@protodeep I cloned the latest `master` of Scaffolds and wasn't able to reproduce this problem; I filled layers down to User Layer 19 and all of them show up in the dropdown.

Can you confirm you're able to reproduce the issue on your machine, and if so, can you confirm that e.g. an editor restart or cache clear doesn't solve the problem?

**Comment by nickjbenson** [comment]
Barrett confirmed could-not-reproduce, so I'm suspecting we were just seeing some funky editor state going on. Closing this.
