### ISSUE TITLE
LeapC.dll C++ Redist 2017 Dependency

### ISSUE THREAD

**Issue by Corobi** [leapmotion/UnityModules#922]
I've had an issue running VR Visualizer Unity app on a new Windows 10 machine, whereby the tracking status is all nice and green in the control panel and the diagnostic visualiser is correctly tracking the hands. When running the Unity VR Visualizer however, it complains that the device is not connected.

It seems that leapC.dll now depends on msvcp140.dll. There are no other clues that it does, other than renaming the file and trying to relaunch the app. If I replaced LeapC and LeapCSharp dlls with older versions, the app launches correctly too.

After installing the C++ redist 2017, VR Visualizer started up and ran as normal. My Unity app suffered the same issue of the hands not tracking, but everything appeared normal in the control panel.

I assume that LeapC is using LoadLibrary as when running it through depends.exe, it doesn't find any dependency on the library, and therefore doesn't error on load.

Could the redist be included to the SDK installer at all to ensure it is present? Or some other indication it is required perhaps?

**Comment by Corobi** [comment]
Video to help explain: https://www.dropbox.com/s/zdk6bymhj56yl7u/LeapMotionDependency.mp4?dl=0

**Comment by nickjbenson** [comment]
Thanks for flagging this issue. The latest SDK release is out-of-sync with the UnityModules release and doesn't include the 2017 redistributable yet in its install, which is required with the latest UnityModules. The next SDK release will include the redistributable and will resolve this issue.

If anyone else hits this problem, you can download the required redistributable in the mean-time at the bottom of the VS downloads page:
https://www.visualstudio.com/downloads/
