### ISSUE TITLE
CompressibleUI memory leak in Update in Unity

### ISSUE THREAD

**Issue by twisty01** [leapmotion/UnityModules#934]
Hi, 
I suspect the CompressibleUI component is leaking memory in Update. It's few kB in 1 frame, but when using a lot of CompressibleUI components, it can cause trouble. I used Unity profiler to mesure it.
 
Edit: could be caused by Unity UI components

**Comment by Amarcolina** [comment]
Make sure that you do profiling in a build rather than inside the editor.  In particular simple things like calls to GetComponent can cause garbage in the editor but _not_ in builds.
