### ISSUE TITLE
Unity 2017.3 Module

### ISSUE THREAD

**Issue by Naphier** [leapmotion/UnityModules#937]
We're looking at the Unity 2017.3 early release. Can you guys tell me what the differences are in the 2017.3 zip (UnityModules-release-4.3.4.zip) in comparison to the current sdk for Unity 5.6?

**Comment by Amarcolina** [comment]
The description of [The Release PR](https://github.com/leapmotion/UnityModules/pull/931) has a list of all of the changes compared to the previous release.  Were there specific areas you had questions on, or more specific answers you wanted?

**Comment by Naphier** [comment]
That should do it, thanks. I think the confusion was that on the site it alludes to it being a special release for 2017.3.
