### ISSUE TITLE
error CS0246: The type or namespace name `IHandModel' could not be found. Are you missing an assembly reference?

### ISSUE THREAD

**Issue by aaronyih1** [leapmotion/UnityModules#939]
Upon downloading the early access release for unity 2017.3, right out of the box when running the interaction example, I get this error.

**Comment by Amarcolina** [comment]
All of the modules in addition to core must be upgraded in order for complete compatibility with 2017.3.  Is is possible you only updated some of them?  Where are you getting this early access release?

**Comment by jselstad** [comment]
You have to delete your old LeapMotion folders before installing the new one.

**Comment by nickjbenson** [comment]
You can check the wiki for module upgrade instructions; it's probably also better to post non-release and non-`develop` comments or issues on the relevant PR itself.

(Closing.)
