### ISSUE TITLE
Hand misaligned to images in Unity Visualizer

### ISSUE THREAD

**Issue by jo3w4rd** [leapmotion/UnityModules#95]
If the service is not running when the scene is started, and then started, the hands and images become misaligned. Unity also throws an exception. This only seems to happen in the Visualizer scene, not, for example, the AR scene.

MissingReferenceException: The object of type 'LeapImageRetriever' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Component.GetComponent[Camera] ()
Leap.Unity.LeapImageRetriever.ApplyCameraProjectionValues () (at Assets/LeapMotion/Scripts/LeapImageRetriever.cs:351)
Leap.Unity.LeapImageRetriever.HandleOnValidCameraParams (CameraParams camParams) (at Assets/LeapMotion/Scripts/LeapImageRetriever.cs:287)
Leap.Unity.LeapVRCameraControl.OnPreCull () (at Assets/LeapMotion/Scripts/VR/LeapVRCameraControl.cs:81)

![bugvisualizermissalignment](https://cloud.githubusercontent.com/assets/2576138/13998189/27b89a82-f0f3-11e5-9c75-591788ae0a36.png)

**Comment by testmasterbright** [comment]
Interesting... we encountered this issue prior to the Orion release and @Amarcolina was able fix it. Not sure how it was reintroduced. It is fine on Elderberry but I believe the visualizer package on develop hasn't been updated since Orion launch. It definitely needs to be updated for the next release.

**Comment by jo3w4rd** [comment]
This was caused by problems with getting device information, which turned off the VRTemporalWarping feature.
