### ISSUE TITLE
Large velocities in Soft Contact when the system is prevented from auto-disabling

### ISSUE THREAD

**Issue by vabrador** [leapmotion/UnityModules#963]
In creating #961, @jselstad encountered problematic soft contact behavior when he removed Soft Contact's auto-disable timer for debugging purposes:

>As far as the root cause of the issue... I don't fully know. To @Amarcolina 's question, I had been testing the soft contact by disabling the disable call to it, but it seems like the bugs I was getting only appeared when I disabled Soft Contact's ability to disable itself (and go away when it's allowed to enable and disable itself...)

I laid eyes on this bug as well; it seemed to happen more reliably when a second interaction hand entered the scene. Objects touched by a hand forcibly kept in soft contact mode would receive large forces from the soft contact system.

When we have some better graphing utilities or build out more test infrastructure for the Interaction Engine, this is a prime stress case: Can we reproduce it, and can we find out when the large velocities are introduced in the soft contact pipeline?

**Comment by MaxPalmer-UH** [comment]
Closing here. Tracking as UNITY-758
