### ISSUE TITLE
Add FPS counter to the Unity VR Visualizer

### ISSUE THREAD

**Issue by testmasterbright** [leapmotion/UnityModules#98]
##### Description:
Hyoung recently added a Data FPS and Render FPS to the SamsungVR demo (https://github.com/leapmotion/UnityModules/pull/88). This should be easily ported to the VR Visualizer.

**Comment by digitalweaver** [comment]
@protodeep This is the Data FPS we talked about last week that you mentioned you could get into the 1.3 visualizer this week. Does that still work for you?
