### ISSUE TITLE
Realistic hands

### ISSUE THREAD

**Issue by Naphier** [leapmotion/UnityModules#981]
From: https://developer.leapmotion.com/unity#116
> Hands Module (2.1.3)
> Provides a range of realistic and low-poly rigged hand models, plus the power to design your own with an autorigging pipeline.

Where are the "realistic" hand models? None of the ones in the package are realistic and are all non-human. If you guys aren't providing realistic hands then please change the wording on your website to be less misleading.
Thanks!

**Comment by acolgan** [comment]
Resolved!
