### ISSUE TITLE
Serialization of a Frame

### ISSUE THREAD

**Issue by harraps** [leapmotion/UnityModules#984]
Hello,

I have a problem with serializing a frame I acquired from the LeapServiceProvider in my Unity project.

I have imported the `LMHeadMountedRig` into my scene and I've added a custom script on `LeapHandController`
```csharp
using System;
using UnityEngine;
using Leap;
using Leap.Unity;

public class LeapPlaybackTest : MonoBehaviour {

    LeapHandController m_ctrl;
    LeapProvider m_prov;
    HandPool m_pool;

    bool wrote = false;
    
    void Awake () {
        m_ctrl = GetComponent<LeapHandController>();
        m_prov = GetComponent<LeapServiceProvider>();
        m_pool = GetComponent<HandPool>();
    }
	
	void Update () {

        // get a frame
        Frame frame = m_prov.CurrentFrame;
        if (frame == null) return;

        try {

            // clone the frame to avoid loosing it
            frame = new Frame().CopyFrom(frame);

            // display if there is some data in it
            Debug.Log("hand count: " + frame.Hands.Count);

            // try to serialize the frame only once
            if (wrote) return;
            byte[] serializedFrame = frame.Serialize;
            System.IO.File.WriteAllBytes("frame.data", serializedFrame);

            wrote = true;
            Debug.Log("Written !");

        } catch (Exception e) {}
    }
}
```

I just try to get the serialized content of one frame as an array of byte (`byte[]`). I've followed the examples online and I've checked on the forum to see if anyone else had the same issue as me.

If I remove the try catch from my code I get the following error.
```
IndexOutOfRangeException: Array index is out of range.
Leap.Frame.get_Serialize ()
```

I also tried to look into the C# code of Leap.Frame but since it isn't implemented in C#, I cannot see either what the problem could be.

If it is possible to have a quick fix or if you could explain how I can Serialize and __Deserialize*__ the frame myself, I would greatly appreciate it. Thank you.

__*__ _How to deserialize and how should I applied the data to a new capsule hand model._

**Comment by Amarcolina** [comment]
My apologies, that method is actually _completely unimplemented_ and does nothing but throw an error!  There is no existing straightforward way to serialize a frame into a byte array, but since the Frame should be marked as serializable you should be able to use normal C# serialization to get the result you want.

**Comment by harraps** [comment]
So by using a `BinaryFormatter` and a `Stream` I should be able to serialize the frame and send it over the network ?

**Comment by Amarcolina** [comment]
Yes indeed that should be possible!  Let us know if that approach gives you any trouble.  We have a couple of ideas in the pipe for more efficient binary representations of the Frame, but I don't think any of them are ready to try out or experiment with yet unfortunately.

**Comment by harraps** [comment]
[leap_frame.txt](https://github.com/leapmotion/UnityModules/files/1860529/leap_frame.txt)

I have tried your method, but the frame contains some useless clear text. They take up to 25% of the whole frame which is kind of a waste.

Either way, I think I will stick with this solution for now. I suppose once the serialization will be implemented, we will be able to transmit smaller packets (and maybe in UDP).

**Comment by gamodulon** [comment]
Hi, is serialization of Frames going to be implemented in Unity modules in the future?
I am developing a Unity project which needs to record and playback hands (similar to leapjs-playback).
Is there another way to accomplish this?

**Comment by MinatoN1345** [comment]
Really inconvenient.
