### ISSUE TITLE
Add a "Leap Motion Settings" window a la SteamVR

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#986]
We already have a preferences pane. This could duplicate or replace the settings available in that window, and should probably allow module self-declaration in a similar way to preserve code.

Requirements for this window:

- [ ] Should not take up unnecessary space in the menu bar -- can be beneath Window (what is SteamVR's menu path?)
- [ ] Core: Hotkey preferences should be configurable here (Ctrl+E, Ctrl+Shift+E)
- [ ] GR: Graphics limit and any other GR options configurable here
- [ ] IE: preferences should be configurable here (if any)
- [ ] IE: on-first-run alerts should be replaced with opening the settings window with IE warnings clearly visible for physics settings: Gravity and Timestep specifically. These alerts should have auto-fix buttons.
- [ ] Core: The rig auto-upgrader script should detect old rigs here when a scene is open and have an auto-fix button to upgrade the rig.

**Comment by Amarcolina** [comment]
> This could duplicate or replace the settings available 
The preferences window is currently attribute based, so we could probably duplicate all of the preferences without any effort at all.  The currently preferences basically can draw all the preferences given a GuiLayout context.

**Comment by nickjbenson** [comment]
Partially addressed by #1011, but will still need Interaction Engine project checks.
