### ISSUE TITLE
Add rig auto-upgrader script from old Leap rigs to new rigs.

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#987]
Since we simplified the hierarchy of a Leap rig to essentially just be a normal VR rig, we don't want developers to have to deal with the old, more complicated rig setup.

- [ ] Detect old Leap rigs, file an alert with the LM settings window, and include a button to auto-upgrade the rig.
- [ ] This detection should at a minimum automatically run when a scene is loaded in the editor. (It may be impractical to try to run the detection for all serialized scenes.)
- [ ] Test the auto-upgrader on older projects e.g. deprecated DetectionExamples module and Blocks
- [ ] Extraneous scripts that may have been attached to the rigs should be preserved wherever possible.
- [ ] We must double-verify that rig upgrading is an Undo-able operation.
- [ ] We should duplicate and disable a backup rig first in case the user wants to modify the result and have the old rig as a reference.

**Comment by Amarcolina** [comment]
We also need to scan the scene for references to scripts/transforms/game objects that get moved or deleted during the process, and do something intelligent with them

**Comment by nickjbenson** [comment]
Need is a strong word :P it's a good idea and we can probably include that in the tool. References to a HandModelManager will likely be preserved just fine, LeapServiceProvider references that were made null after the operation can most likely be safety transferred to the XR service provider.

Thinking about a thorough list in this style:
- References to Main Camera in the old rig -> Main Camera in the new rig
- References to LeapController (LeapServiceProvider or LeapXRServiceProvider) in the old rig -> Main Camera (Leap XR Service Provider in the new rig)
- References to HandPool or HandModelManager (the same) in the old rig -> should require no action

Internal to the new rig, we would just make sure the HandModelManager gets the new XR service provider hook-up.

**Comment by Amarcolina** [comment]
Doesn't matter if a component doesn't change, if it gets moved from one gameobject to another, _all_ of the references pointing to it will be broken.  So in this case, we would also need rules for user scripts that exist on a game object that is being removed, and where to move that script (and update the references)

**Comment by nickjbenson** [comment]
We would move objects, not components, wherever possible. The HandPool/HandModelManager only moves location during the upgrade, the component itself doesn't get moved :D so we should just win on that one

**Comment by nickjbenson** [comment]
Shoot, you're right. Editing

**Comment by nickjbenson** [comment]
Address by #1011 once merged.
