### ISSUE TITLE
Desktop Mode text should be changed to reflect HMD mode toggle

### ISSUE THREAD

**Issue by testmasterbright** [leapmotion/UnityModules#99]
##### Description:
The Desktop and HMD Tracking Modes toggle but the text at the top does not. 

![desktopmode](https://cloud.githubusercontent.com/assets/6034882/14032415/ed7204de-f1cf-11e5-84ca-3cbacfb2aad9.png)

**Comment by protodeep** [comment]
After discussion with Matt & Caleb, plan is to remove top label since it can ultimately add confusion.
