### ISSUE TITLE
(UWP) can not compile C# script

### ISSUE THREAD

**Issue by toriop** [leapmotion/UnityModules#996]
I use unity2017 with leapmotion core assets 4.3.4;
But I still has the compile error when I want to compile C# script in unity, what should I do?

![image](https://user-images.githubusercontent.com/37078704/38506596-9ca1a14e-3c1a-11e8-9e89-bc6f478776a1.png)
or maybe I have any problems in my setting?

![image](https://user-images.githubusercontent.com/37078704/38506673-cfed81e4-3c1a-11e8-9845-d64731e47034.png)

**Comment by Amarcolina** [comment]
Also see #926 for reference

**Comment by Amarcolina** [comment]
Going to close this for now, since UWP support is not currently on our roadmap.

**Comment by antoson** [comment]
> The short reason we don't support UWP as a target is that UWP does not support win32, which our Windows service relies on.

Now that [Project Reunion](https://docs.microsoft.com/en-us/windows/apps/project-reunion/) allows to combine UWP and Win32, do you think targeting UWP could be achieved?

Currently, I'm trying to work around this issue by embedding a Standalone x64 Unity exe inside a .NET Core 3.1 WPF app (using [-parentHWND](https://docs.unity3d.com/Manual/CommandLineArguments.html)), and using XAML Islands to host  the UWP controls in WPF.
